### ISSUE TITLE
[Bug] Custom Size is making the window ribbon load out of bounds

### ISSUE THREAD

**Issue by Daisouji** [TASEmulators/BizHawk#3441] opened 2022-11-06 00:23 UTC
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
If I put the custom size beyond 1200 by 900, The Window Ribbon will load of bounds
### Repro
1)  Do any dimension beyond 1200 for Display/Custom Size
2) Confirm and Restart the program

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.8 Win 10 (Latest Version)

**Comment by YoshiRulz** [comment] 2022-11-06 00:25
Duplicate of #2850?

**Comment by Daisouji** [comment] 2022-11-06 00:30
> Duplicate of #2850?

Ohh Sorry for the duplicate.

**Closed** 2023-09-15 15:39 UTC
Labels: App: EmuHawk, Repro: Affects 2.8
