### ISSUE TITLE
Bizhawk all versions 2.7 included - Error messages when opening from another software ex : Romstation to Bizhawk

### ISSUE THREAD

**Issue by PegHorse** [TASEmulators/BizHawk#3025] opened 2021-12-09 14:23 UTC
```
System.ObjectDisposedException: Impossible d'accéder à un objet supprimé.
Nom de l'objet : 'MainForm'.
   à System.Windows.Forms.Control.CreateHandle()
   à System.Windows.Forms.Form.CreateHandle()
   à System.Windows.Forms.Control.get_Handle()
   à System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   à System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   à System.Windows.Forms.Control.Show()
   à BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

This occurs when Bizhawk is already opened, so the game is loading anyway but everytimes, this message occurs and i have to press OK to start Playing.

edit: With single-instance mode enabled, crashes. With it disabled, a new instance is launched as expected.

No matter the Emulation : Master System, Nintendo, etc...

If Bizhawk was closed, then no error and all is OK
So it's not critical as i still can play and the game is loading anyway but i don't understand why it's happening.

I send my games from Romstation to Bizhawk directly.
Thanks

**Comment by YoshiRulz** [comment] 2021-12-09 14:24
Is `Config` > `Customise` > `Single-instance mode` enabled?

**Comment by PegHorse** [comment] 2021-12-09 14:25
Yes it's already Enabled, i had same idea before to open this issue.

**Comment by CasualPokePlayer** [comment] 2021-12-09 15:52
What did you expect from a mode that only allows a single BizHawk instance active, the ability to have multiple instances active?

**Comment by PegHorse** [comment] 2021-12-09 17:39
Is it a real question or a troll question ?
If i'm reporting a bug because my setup have the option "Single Instance" Enabled since beginning in customise menu, what did i expect ?
To have windows errors or just to load immiadely the new game on the same window without bug ?

If the option is disabled of course there is no bug message anymore but i have a new instance of Bizhawk which i don't want.

**Comment by CasualPokePlayer** [comment] 2021-12-09 23:09
Is this an issue purely pertaining to this "romstation" or can it happen with other software. At a glance this romstation is effectively a pirating machine with ROM downloads which we obviously will not bother fixing whatever broke it.

**Comment by PegHorse** [comment] 2021-12-09 23:48
I don't know. I use only Romstation.
But Romstation is not pirating machine as it's legit, they are denying/deleting illegal ROMs so obviously you don't know them. 
Regardless legit or not is not your business anyway but mine, my responsability only.

Also, Romstation launch Emuhawk pointing directly to the ROM file but for some reasons, if there is already an instance of Emuhawk which is running, there is this error message if we do not allow Multiple instances so this fix is required if you expect to offer quality software.

If you do not want to fix it well i'll play with another software which is not bugged and i'll put bad review.
You probably don't care well in this case i'll tell you : stop development, delete the source code and everythings you made.

I wanted to trust Emuhawk due to multi-emulation machines...

**Comment by CasualPokePlayer** [comment] 2021-12-10 00:23
I stated that was the impression at a glance, as they appear to offer ROM downloads. Which is piracy. If legit here is they do what they claim, then sure, they're legit, but also offering a service which is not legal under USA laws (which GitHub/TASVideos are bound under as USA entities).

Of course, if I'm mistaken and they do not offer ROMs and the user is expected to provide all of those files themselves via other sources (which I'm not seeing that), then that is perfectly legal.

Also, BizHawk is developed by many different people, and any person could fix whatever issue this is; it's obviously a lot less of a priority for us in general if the issue is only happening towards some illegal software which we would not want to associate with.

**Comment by PegHorse** [comment] 2021-12-10 00:55
Romstation is a French service that offer players to Re-Download ROMs which doesn't have any licence anymore due to the legal abandon.

If somehow someone upload an illegal ROMs, will be immediately removed/denied, all are moderated.
Nobody can't upload without legal checks and admin/moderators approvals.
It's been created so users can rebuild their collection and play them again with PC.

It exists since many years, as SEGA, Nintendo, etc... are extremely agressive against piracy, such service would have be down very quickly especially in France faster than in US if there would be some illegals issues.

As i've said before, Romstation is not associated with Emuhawk, i've just setup Romstation to launch Emuhawk when i click "Run" to the ROM. I could launch any software but i would rather have multi-emulators software than single one per console.

So your concerns are irrelevants and as i said before is absolutely not your business at all.

Also i believes it's an easy fix for you because it's only showing when Emuhawk is already loaded and "Single Instance" enabled.
If i close the software before to Run the ROM, the error doesn't occur.

**Comment by CasualPokePlayer** [comment] 2021-12-10 01:58
That's not how copyright works. The authors would have to explicitly release their product into the public domain to remove all copyright. Otherwise, they stay copyrighted until they naturally are released into the public domain, which all video games have not at all reached that time. You're probably describing abadonware, which is still piracy, but the copyright holders probably will not enforce any copyright claim.

Still, this isn't something emulators want to associate with either way. It is our business if this software is the only problematic one and if others are fine. Prioritization won't happen for issues specific to software like this.

**Comment by PegHorse** [comment] 2021-12-10 02:04
It happens with Windows too (Windows 10 here)
If i'm running directly the ROM with Explorer "open with, Emuhawk" and Emuhawk is already loaded, same error occurs.
You can check/test it easily.

**Comment by TiKevin83** [comment] 2021-12-10 02:51
To be clear, I don't see how the issue as described is a bizhawk issue, It's up to ROMStation to invoke hawk with the option set as needed if they need multiple instances. Bizhawk should handle the exception more gracefully and alert the user about the config for multiple instances, but it's not possible for us to fix how ROMStation sets up the config. Another issue would be to explore changing the default in the config, but I think it's more likely that single instance should be the default

**Comment by PegHorse** [comment] 2021-12-10 03:01
As i said, it's happening with Windows Explorer too.
By default "Single Instance" is not Enabled, i did it because i don't want to open multiples instances...

With Windows "Right click to Any ROM, Open With, EmuHawk" and you've got the error, you press OK and the game is launching anyway if Emuhawk was already opened so it's a proof it's not related to specifically Romstation. I think Romstation invoke command to Windows to run the ROM too.

So you can generate the bug easily with your system, just repeat exactly the process like me.

**Comment by YoshiRulz** [comment] 2021-12-10 03:37
WTF is all this off-topic nonsense. The entire purpose of single-instance mode is to handle opening roms from the Windows shell, Firefox, or whatever Steam+retro game launcher is popular this year.

**Comment by TiKevin83** [comment] 2021-12-10 04:53
Is the intended behavior then that if hawk is already running and someone tries to open with Emuhawk from file explorer it switches to the other ROM?

**Comment by YoshiRulz** [comment] 2021-12-10 04:57
https://github.com/TASEmulators/BizHawk/blob/967ef7c99586272de7345b38bafba8991d20579b/src/BizHawk.Client.EmuHawk/MainForm.cs#L4816-L4825

**Comment by PegHorse** [comment] 2021-12-10 05:50
> 

Yes it is. I expected the program switch to the other ROM directly instead of a message asking to close the current instance.

**Comment by PegHorse** [comment] 2022-01-29 15:27
Will you fixe this bug before version 2.8 stable ?

**Comment by YoshiRulz** [comment] 2022-02-02 12:55
Fixed in https://github.com/TASEmulators/BizHawk/commit/cff2b04dccd3132fcf33e7a94ce2804e250bfd7e.

**Closed by YoshiRulz** 2022-02-02 12:55 UTC
Labels: App: EmuHawk, Repro: Fixed/Added in 2.8 dev, Repro: Affects 2.7

**Comment by PegHorse** [comment] 2022-02-02 15:33
Is there anyway to download the last build to test your fix ?
It seems it's not possible

Tried with this one : "https://ci.appveyor.com/api/buildjobs/b1mgjnxa4g98icsu/artifacts/BizHawk_Developer-2022-02-02-124713-%23cff2b04dccd3132fcf33e7a94ce2804e250bfd7e.zip"

Download limit exceeded while i still didn't pick anything.

**Comment by TiKevin83** [comment] 2022-02-02 15:36
Builds are available via GitLab CI artifacts (right hand side of this page)

**Comment by PegHorse** [comment] 2022-02-02 15:55
Confirmed it's working now, thanks :)
