### ISSUE TITLE
Only SameBoy can load some homebrew ROMs

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3245] opened 2022-05-15 11:18 UTC
In Gambatte, the "Core Reported BoardID" retuns "NULL" (seen in build_asms_debug build) with a lot of spaces in the log window when trying to load some homebrew ROMs. This makes it IMPOSSIBLE to load some homebrew DMG or CGB ROMs with Gambatte. Affected ROMs (I found):
sierpinskiboy.smol.cgb (0x150 size patch)
seems to relate to #3244 but it is locked

**Comment by CasualPokePlayer** [comment] 2022-05-15 16:30
The issue isn't that NULL has a "lot of spaces" (really it's just a ton of zeros". In fact Gambatte starts up just fine. "NULL" too just means ROM only (i.e. no mapper present).

The "issue" here is Gambatte just loads in every full ROM bank then pads 0xFFs until it's a power of two. 0x150 is smaller than a full ROM bank so it just copies in nothing and 0xFFs the entire ROM space.

**Comment by getCursorsExe** [comment] 2022-05-24 18:59
I patched the ROM again and it works.

**Comment by CasualPokePlayer** [comment] 2024-05-31 00:12
I'd just call this a "won't fix", it's not sensible to have a non-power of 2 size in the first place (real ROMs cannot be less than a power of 2, and homebrew normally pads out to a power of 2 as expected), and Gambatte expects a header at the very least (which a homebrew maker would have to do manual/custom work to not have happen in the first place). SameBoy having code handling this extremely odd ROM is their prerogative, and that's at least an option for users.

**Closed by CasualPokePlayer** 2024-05-31 00:12 UTC
Labels: App: EmuHawk, Core: Gambatte, Homebrew
