### ISSUE TITLE
Mega CD / Sega CD - USA Firmware SCD_us_9303.bin Freezes - Listed as "Good" Firmware in DB

### ISSUE THREAD

**Issue by boktai1000** [TASEmulators/BizHawk#3147] opened 2022-02-15 16:40 UTC
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."

This firmware when loaded by BizHawk causes the Mega Drive to freeze completely. This behavior is described in the Bizhawk readme here: https://github.com/TASEmulators/BizHawk/blob/master/waterbox/picodrive/platform/base_readme.txt

The problem I see is that the firmware is actually listed as valid/OK in the firmware database for Bizhawk when searching for it's MD5 Hash `BD3EE0C8AB732468748BF98953603CE772612704` or by the filename `SCD_us_9303.bin`

https://github.com/TASEmulators/BizHawk/blob/master/src/BizHawk.Emulation.Common/Database/FirmwareDatabase.cs#L214

`			var us_scd2_9303 = File("BD3EE0C8AB732468748BF98953603CE772612704", 131072, "SCD_us_9303.bin", "Sega CD US (9303)");`

The main issue I see, is I don't believe this firmware is good in any situation. BizHawk loads it, but it crashes and does nothing. So I see this as identifying a known bad dump that seems at least one other emulator has also identified and blacklisted. It's also noted in the BizHawk readme that a bad dump can cause this, so I wouldn't think a bad dump should be listed as "Good" in the Bizhawk firmware DB.

When I look this hash up online, I can find a few references to this dump causing issues. A few in particular can be seen here when referencing it in Mame:

https://github.com/mamedev/mame/blob/master/src/mame/drivers/megadriv.cpp

```
	/* this is reportedly a bad dump, it has many differences from the verified dump and does not boot in Kega */
	/* ROMX_LOAD( "segacd_model2_bios_2_00_u.bin", 0x000000,  0x020000, CRC(340b4be4) SHA1(bd3ee0c8ab732468748bf98953603ce772612704), ROM_BIOS(1) ) */
```

There are a few of anecdote articles as well on Reddit of users encountering this behavior recently in Bizhawk as well, likely due to this firmware being distributed and accepted in Bizhawk.

https://www.reddit.com/r/SegaCD/comments/qalu3h/issues_with_running_usa_sega_cd_games_on_bizhawk/

The firmware itself commonly goes by a few a few different names, but the name is a bit arbitrary of course:

```
SCD_us_9303.bin
segacd_model2_bios_2_00_u.bin
```

The firmware which has the following hashes:

```
MD5 6845579BD211E24EAFE313933E6F8D7B
SHA1 BD3EE0C8AB732468748BF98953603CE772612704
SHA256 2C5358FCD8F2DF22E14179426BE6E30B466FB4134B6A397725A32F95A0B895D3
```

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."

1. Install the firmware file as described above with the following hashes into BizHawks firmware folder
2. Attempt to load any USA based Sega CD game which will cause BizHawk to load and hang at the BIOS

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.7.0; Win10 Pro 21H1; Intel/Nvidia

[//]: # "(screenshots, if applicable)"

![image](https://user-images.githubusercontent.com/9054563/154107001-13e47d66-15f1-4e07-88cc-f824898280b6.png)
![image](https://user-images.githubusercontent.com/9054563/154107070-932fc849-0dbb-475f-bbdb-4796be5098c0.png)

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by mooware** [comment] 2022-02-15 23:54
I can reproduce the issue, tried both Wonder Dog and Sonic CD, with firmware sha1:F4F315ADCEF9B8FEB0364C21AB7F0EAF5457F3ED the games start, with sha1:BD3EE0C8AB732468748BF98953603CE772612704 it just freezes at the start screen of the Sega CD BIOS.

**Comment by YoshiRulz** [comment] 2022-02-16 04:05
Duplicate of #2913. This revision being blocklisted in MAME is an important point here, thank you.

**Closed by YoshiRulz** 2022-02-16 04:05 UTC
