### ISSUE TITLE
[Octoshock] Bioses, Game Regions and You.

### ISSUE THREAD

**Issue by Spikestuff** [TASEmulators/BizHawk#2474] opened 2020-11-10 13:47 UTC
Ok. So let's say hypothetically that you're someone who just forces the bios for J/U/E to be the same and not care about that.
There's 2 things that happens on a real console.

1. It will take you to the bios' Main Menu screen in the bios and will not boot the mismatched game with the bios.
![PSMainMenu](https://user-images.githubusercontent.com/12412764/98680047-f9628180-23b4-11eb-8e18-79110b0c514e.png)

2. On a modded PlayStation the game will boot, however it will display that they're different in the bios.
![JonUPS](https://user-images.githubusercontent.com/12412764/98680319-5a8a5500-23b5-11eb-9a72-31a3cbba9428.png)
An NTSC-J game is being played on a NTSC-U console it's displaying _Sony Computer Entertainment **Inc** / SCE**A**_.

For a game in the right region it would say _Sony Computer Entertainment Inc / SCEI_ or _Sony Computer Entertainment America / SCEA_ respective to the region being used.

**This is where the issue comes in.**
BizHawk will not treat it like this. Instead it will boot as if it was normal and doesn't help the indication of wrong region, wrong bios.
(And for the ha, ha funny: A PAL bios would be a black screen through the bios when an NTSC-U/J title is being loaded and will then boot into the game. A modded console would not be a black screen, a vanilla console will again take you to the bios' main menu.)

---

Upstream's solution is to throw an error that it's wrong entirely and to tell the user to actually get the correct bios.
![mednafensolution](https://user-images.githubusercontent.com/12412764/98681300-aab5e700-23b6-11eb-9a01-03f743b7714a.png)

RetroArch's solution to compare with their beetle core is to do that of the first thing listed which is to take you to the bios' main menu a thing an actual PlayStation console would do.

**Comment by nattthebear** [comment] 2020-11-10 14:05
> So let's say hypothetically that you're someone who just forces the bios for J/U/E to be the same and not care about that.

Is this what Bizhawk does by default out of the box, or do you need to force firmware customizations to get this effect?

**Comment by Spikestuff** [comment] 2020-11-10 14:24
> or do you need to force firmware customizations to get this effect?

natt... you quoted me and the bit I said that has that answer...
> who just forces the bios for J/U/E to be the same

---

Anyways to expand:
No Hawk doesn't do it out of the box, it will request for you to grab the correct bios and will automatically scan for the right bios.
If you don't have the [mednafen recommended bioses](https://mednafen.github.io/documentation/psx.html#Section_firmware_bios) it will not look for your alternatives even if it's satisfactory.
(So for example. If I have the ps-22 (SCPH100X) bioses instead of ps-30 (SCPH550X) available in my firmware folder, it will not select the ps-22 automatically. You have to force it.)

This is hypothetically saying that you're someone who would force it anyways cause you got that single bios and you're using that for each region despite it being wrong.

**Comment by nattthebear** [comment] 2020-11-10 14:30
I think we should take no action on this.  Sensible defaults give sensible default behavior, tinkering with settings gives power users opportunities to do potentially invalid things.  That's all fine.

**Comment by YoshiRulz** [comment] 2020-11-10 15:43
To be clear, this:
> If you don't have the mednafen recommended bioses it will not look for your alternatives even if it's satisfactory.
> —https://github.com/TASVideos/BizHawk/issues/2474#issuecomment-724734712

...is a bug. The intended behaviour is to tell the user that the non-recommended BIOSes aren't supported, see #2224. Once that gets fixed, it seems more reasonable to call this user error and to not bother with getting system menus working.

In the meantime we could add a warning box like upstream, giving users the choice to open the Firmware Manager, load the rom anyway, or cancel loading.

**Comment by nattthebear** [comment] 2020-11-10 16:02
Adding information in the firmware manager is preferable to bolting on another special case interrupt in the middle of romloader.  If done, wouldn't that fix this problem entirely?  If you have a (U) game, Bizhawk gives the (U) bios choice,, and if you've customized the (U) bios choice to actually be an (E) bios then you would have been punished on the firmware manager when you made this change.

**Comment by YoshiRulz** [comment] 2020-11-10 16:20
True, it only needs to be the missing firmware warning like for Saturnus.

**Comment by YoshiRulz** [comment] 2021-04-04 05:55
Pushed d0a6817c1, resolving #2224; are we calling this user error?

**Comment by YoshiRulz** [comment] 2021-04-05 03:57
> Upstream's solution is to throw an error that it's wrong entirely and to tell the user to actually get the correct bios.
> ![mednafensolution](https://user-images.githubusercontent.com/12412764/98681300-aab5e700-23b6-11eb-9a01-03f743b7714a.png)

This is a front-end feature, and one that we should probably copy. Whoever wired up the firmware seemed to think so too:
https://github.com/TASVideos/BizHawk/blob/d0a6817c1a0dea6926274618b2d869a82a3b2be1/src/BizHawk.Emulation.Cores/Consoles/Sony/PSX/Octoshock.cs#L188
Thing is, the `CoreFileProvider` only returns the raw bytes to the (Hawk-side) core, there's none of the metadata from the `FirmwareDatabase`. I suggest we add a param `bool disallowUnacceptable` to `GetFirmware` and have `CoreFileProvider` do the check.

**Comment by CasualPokePlayer** [comment] 2022-02-02 20:52
Noting here, [Nymashock](https://github.com/TASEmulators/BizHawk/commit/d6b33fbec6ba2ad8f3e26f4ec36be21b1af92b11) leaves upstream's BIOS checks enabled by default and so would do the error thing by default.

**Comment by YoshiRulz** [comment] 2023-03-25 09:42
Regarding the missing warning dialog: Unacceptable firmware is marked as such, and this only affects Octoshock, so #wontfix.

Regarding the accuracy to hacked consoles: #wontfix :P

**Closed by YoshiRulz** 2023-03-25 09:42 UTC
Labels: Core: Octoshock, As intended / #Won'tFix, Inaccuracy
