### ISSUE TITLE
TAStudio will save even when you press "no" in certain cases

### ISSUE THREAD

**Issue by RetroEdit** [TASEmulators/BizHawk#4065] opened 2024-09-28 21:54 UTC
I just had this happen and I was trying to figure out how to trigger it. Separate from #4063 because it happens even if auto save is turned off.

Seems like this happens when you close the EmuHawk window without closing the TAStudio window first and have recording mode enabled. It will prompt "Do you want to save?" but it will save even if you press no.

### Host env.
- BizHawk 2.9.1
- BizHawk dev build at ed676cda391d25bdb1728ada13b7df21c0a974df; Win11

**Comment by YoshiRulz** [comment] 2024-09-28 22:08
wat
https://github.com/TASEmulators/BizHawk/blob/ed676cda391d25bdb1728ada13b7df21c0a974df/src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.IToolForm.cs#L135-L141

**Comment by RetroEdit** [comment] 2024-09-28 22:25
Hm. Very reproducible for me with these steps in ed676cda391d25bdb1728ada13b7df21c0a974df

1. Pause emulator
2. Open game (I opened a GB game and configured boot ROM enabled and had the relevant firmware in the 'Firmware' folder)
3. `File > Record movie...`
4. `Tools > TAStudio`
5. Check recording mode checkbox.
6. Unpause
7. Press 'x' on EmuHawk
8. Press 'No' to "Save TAStudio project?"
9. Observe frame length is greater than 0 (or greater than before if you repeat multiple times).

**Comment by YoshiRulz** [comment] 2024-09-29 03:12
The key part seems to be migrating a `.bk2` into TAStudio. If I follow those steps but skip 3) then no file is created.

The `.tasproj` seems to be written when TAStudio loads, and again when quitting EmuHawk.

**Comment by Morilli** [comment] 2024-09-29 14:13
Loading a bk2 into TAStudio does currently save both the bk2 and the tasproj immediately after conversion. It should not save the tasproj again afterwards unless prompted to.

**Comment by Morilli** [comment] 2024-09-29 14:58
I can reproduce both with and without step 3, and looking at the code this also makes a lot of sense:
https://github.com/TASEmulators/BizHawk/blob/ecfeecdb70083c68f9503a4a463a9120e161321d/src/BizHawk.Client.Common/movie/bk2/Bk2Movie.ModeApi.cs#L26-L42

Call stack:
```
Bk2Movie.Save() at D:/GitHub/BizHawk/src/BizHawk.Client.Common/movie/bk2/Bk2Movie.IO.cs:line 14
Bk2Movie.Stop() at D:/GitHub/BizHawk/src/BizHawk.Client.Common/movie/bk2/Bk2Movie.ModeApi.cs:line 33
MovieSession.StopMovie()
MainForm.CheckMayCloseAndCleanup()
...
```

The same thing happens when a normal movie is active and bizhawk is closed.

**Comment by RetroEdit** [comment] 2024-09-29 18:50
Ah, so this is a side effect of movies saving when BizHawk is closed or saving when `Stop Movie` is pressed.

That's not necessarily a bad thing, and probably something that should be left alone until 2.10 releases. But I think similar to what I said in #4063 it would probably be good if these "implicit saves" were saved to a secondary file that's a backup with the opportunity to restore when the movie is loaded next session.

I've also been thinking for a few months now it might be better if Stop Movie were renamed to `Stop and save movie` maybe to reflect how it actually functions.

**Comment by Morilli** [comment] 2024-09-30 22:03
TAStudio has its own logic for handling movie saves on close, so perhaps it's reasonable to expect it to function, independently of what the default movie save logic on close is.

This could be resolved for TAStudio by swapping these two lines:
https://github.com/TASEmulators/BizHawk/blob/08125ae82dc6c327583fb2ecdeb5c2ae2713411f/src/BizHawk.Client.EmuHawk/MainForm.cs#L812-L813

That way, TAStudio's [Closing handler](https://github.com/TASEmulators/BizHawk/blob/15ff0ec2c703d5f21ae963e2b580a7d7048ff5b3/src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs#L1029) would get called before stopping the movie, which in itself would stop the movie without saving.

**Comment by YoshiRulz** [comment] 2024-10-01 00:23
That does look like a bug—consider a Lua script which only works with a movie loaded. Or Basic Bot might be a better example.

**Closed** 2024-10-01 13:40 UTC
Labels: Tool: TAStudio, Reproducible bug, Repro: Affects 2.9.1
