### ISSUE TITLE
WonderSwan core couldn't load SRAM that made by Mednafen itself

### ISSUE THREAD

**Issue by Yave-Yu** [TASEmulators/BizHawk#3632] opened 2023-04-15 03:16 UTC
Here I've played Final Fantasy WSC, the SRAM save file could be loaded by Mednafen itself and Swan.emu that uses Mednafen as core, but why BizHawk couldn't load the save file even though it uses Mednafen too???
[Final Fantasy Save.zip](https://github.com/TASEmulators/BizHawk/files/11238173/Final.Fantasy.Save.zip)

**Comment by CasualPokePlayer** [comment] 2023-04-15 03:30
We have "merged" SaveRAM (which includes SRAM and the EEPROMs in one file), while mednafen would have them split.

I'll call this a dupe of https://github.com/TASEmulators/BizHawk/issues/1659

**Closed by CasualPokePlayer** 2023-04-15 03:30 UTC
Labels: Question/Support
