### ISSUE TITLE
Result of `gui.drawText` is not cleared from canvas when Lua script is disabled

### ISSUE THREAD

**Issue by DerpPrincess** [TASEmulators/BizHawk#3202] opened 2022-04-02 18:08 UTC
### Summary
When using a Lua Script that uses the gui.drawText function, it does not clear the canvas when the Lua Script is disabled (see functions where this does occur such as gui.text). The expected behavior is that it will clear the canvas once it is disabled. As such, I feel this is a bug report. The drawing canvas should not matter (gui.use_surface function).

### Repro
1. Use a Lua Script that uses gui.drawText function
2. See that it draws on the screen
3. Disable the Script
4. See that although the text isn't updating to reflect value changes anymore, as expected, (if that is being used, example HP), the text being drawn is still on the canvas. 

### Host env.
BizHawk 2.8 - Windows 10 Home - Nvidia Graphics / Intel CPU

**Comment by ThunderAxe31** [comment] 2022-12-02 13:38
Duplicate of #3014.

**Closed** 2022-12-02 14:47 UTC
Labels: App: EmuHawk, re: Lua API/scripting, Repro: Affects 2.8
