### ISSUE TITLE
Octoshock: Screenshots have 0 alpha (100% transparent)

### ISSUE THREAD

**Issue by webbedspace** [TASEmulators/BizHawk#3358] opened 2022-08-17 07:14 UTC
### Summary
Taking a screenshot with the Screenshot hotkey in Octoshock produces PNG files where every pixel has alpha 0 (i.e. appears completely blank in most image programs).

### Repro
1. Play game in Octoshock (I tried Moon Remix RPG Adventure and Jikkyou Oshaberi Parodius)
2. Press Screenshot hotkey

### Output
Resulting screenshot:
![Moon Remix RPG Adventure 2022-08-17 16 53 58](https://user-images.githubusercontent.com/83939/185056571-d9ff205b-e04b-4b03-a7fd-eb5fc30924e5.png)
Exact same screenshot with all pixels' alpha changed to 1 (or 255 or whatever the max is):
![image](https://user-images.githubusercontent.com/83939/185057542-5f35a6f2-b80a-4ed1-a469-95e4c34d9325.png)

### Host env.
- BizHawk 2.8; Windows 10

**Comment by YoshiRulz** [comment] 2022-08-17 07:19
Duplicate of #3166.

**Closed by YoshiRulz** 2022-08-17 07:19 UTC
