### ISSUE TITLE
Windows - Open With BizHawk crashes: "path's format not supported".

### ISSUE THREAD

**Issue by Yoshi348** [TASEmulators/BizHawk#2841] opened 2021-07-11 06:59 UTC
### Summary
Trying to open a ROM with BizHawk by dragging the file onto BizHawk or associating the file type with BizHawk is causing a crash in 2.6.2 for me, with a exception that the path's format is not supported. Opening BizHawk and then loading the ROM through its menus is working fine. Had no problems on 2.6.1 with the same setup. Tried multiple systems, reassociation, and working from the same directory as BizHawk itself, with no luck.

### Repro
1. Drag supported ROM file onto BizHawk.
2. Crash.

### Output
```
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at BizHawk.Common.PathExtensions.PathExtensions.MakeAbsolute(String path, String cwd)
   at BizHawk.Client.EmuHawk.MainForm..ctor(Config config, IGL gl, Action`1 updateGlobalSound, String[] args, IMovieSession& movieSession)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

### Host env.
- BizHawk 2.6.2; Win10

**Comment by YoshiRulz** [comment] 2021-07-11 07:21
Duplicate of #2787.

**Closed by YoshiRulz** 2021-07-11 07:21 UTC
Labels: App: EmuHawk, Repro: Fixed/added in 2.6.3, Repro: Affects 2.6.2
