### ISSUE TITLE
[Feature Request] Make a configuration file import tool (ImportBIZ may be)

### ISSUE THREAD

**Issue by Danik2343** [TASEmulators/BizHawk#3627] opened 2023-04-12 08:39 UTC
In this tool, it will be possible to send the old configuration file, the tool will read the configuration version for example 2.8 and taking into account the new version at the moment 2.9 will correct the configuration file for the new version (for example, delete unused lines and so on)
So it will be easier to transfer the configuration, now you can just copy version 2.8 open it and open 2.9 and transfer settings in this way, not a convenient way at all.

**Comment by YoshiRulz** [comment] 2023-04-12 16:40
Going to call this a duplicate of #2094.

**Closed by YoshiRulz** 2023-04-12 16:40 UTC
Labels: Request: Feature/Enhancement, App: EmuHawk
