### ISSUE TITLE
Some cores constantly change bytes even if the game is paused

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3116] opened 2022-02-01 18:54 UTC
This can be seen in Hex Editor. 
Affected cores (I noticed):
BSNESv115+ (bytes xx2138, xx2139, xx213A, xx213B, xx2180 in System Bus are constantly changing, even if paused)

**Comment by YoshiRulz** [comment] 2022-02-01 18:58
see also #3060

**Comment by CasualPokePlayer** [comment] 2022-02-01 19:55
"Some cores"
>One example
The problem here looks like a dupe of the issue linked. It's likely just reading on system bus here is updating state which should not be happening.

**Comment by nattthebear** [comment] 2022-02-01 21:14
> which should not be happening.

Or should be happening? There's no one right answer.  Hex Editors probably shouldn't cause side effects, but a way should exist to do full reads with all side effects.  Do we still not have peak vs read semantics?

**Comment by CasualPokePlayer** [comment] 2022-02-01 21:18
> > which should not be happening.
> 
> Or should be happening? There's no one right answer. Hex Editors probably shouldn't cause side effects, but a way should exist to do full reads with all side effects. Do we still not have peak vs read semantics?

There're no sematics dealing with peek vs read. Perhaps some sort of flag in a memory domain can indicate that reads may be nondeterministic?

The issue here currently is really simply BSNESv115 is just calling `bus.read` for System Bus with no regard to whether that is safe to do. Unsafe parts of memory for peeking should be blocked from reading like old BSNES does.

**Comment by nattthebear** [comment] 2022-02-01 22:37
> The issue here currently is really simply BSNESv115 is just calling `bus.read` for System Bus with no regard to whether that is safe to do.

Which it can never possibly know because that information is not available.  We need actual peak vs read semantics and to stop having cores guess.

**Closed by nattthebear** 2022-02-01 22:37 UTC
Labels: Core: BSNES, Tool: Hex Editor

**Comment by getCursorsExe** [comment] 2022-06-16 19:39
I discovered that HyperNyma is also affected (but it is possibly a waterbox issue at this point).
