### ISSUE TITLE
Certain .gen files go dark and oversaturated

### ISSUE THREAD

**Issue by StickyChannel92** [TASEmulators/BizHawk#3511] opened 2023-01-02 14:05 UTC
### Summary
Some .gen files display the wrong colors, turning down the brightness and oversaturating colors.

### Repro
1. use default settings
2. load Sonic Mega Mix `SHA1:2C41FD7372068FA86B3A1B2DDF03514253D0C2CA`

### Host env.
Bizhawk 2.8 (x64): HP Laptop 17-cn0xxx, 11th Gen Intel(R) Core(TM) i3-1125G4 @ 2.00GHz

![image](https://user-images.githubusercontent.com/48563620/210241496-77f4f58e-e360-40fd-86a0-4e77e0811dfd.png)
![image](https://user-images.githubusercontent.com/48563620/210241815-255f15d6-171b-44aa-ab57-0b70af73eb45.png)

**Comment by YoshiRulz** [comment] 2023-01-02 14:06
Duplicate of #3391?

**Comment by StickyChannel92** [comment] 2023-01-02 15:20
> Duplicate of #3391? edit: also, no copyrighted material please

I'm not sure. This only happened to me before with this one ROM. No other Sonic hack (or any genesis game to my knowledge) has had this issue.

**Comment by getCursorsExe** [comment] 2023-01-02 16:49
Upstream issue. GPGX in RetroArch suffers from this too. The emulator is erroneously making the game clear the M4 bit (2nd bit) of VDP 0x00 register. I suggest to make an setting to force this bit enabled as the current workaround.

Well, I made some experiments with gamedb and file extensions to make BizHawk load this game in BizHawk's PicoDrive.
And, to my surprise...
![image](https://user-images.githubusercontent.com/39802077/210259069-30a61fb4-71a5-4987-a87d-d8ac5f3de2b5.png)
The old, inaccurate PicoDrive core actually gets this correct! Perhaps this core can be used for comparison?

**Comment by StickyChannel92** [comment] 2023-01-03 02:24
> Upstream issue. GPGX in RetroArch suffers from this too. The emulator is erroneously making the game clear the M4 bit (2nd bit) of VDP 0x00 register (every frame, possibly). I suggest to make an setting to force this bit enabled as the current workaround.
> 
> Well, I made some experiments with gamedb and file extensions to make BizHawk load this game in BizHawk's PicoDrive. And, to my surprise... ![image](https://user-images.githubusercontent.com/39802077/210259069-30a61fb4-71a5-4987-a87d-d8ac5f3de2b5.png) The old, inaccurate PicoDrive core actually gets this correct! Perhaps this core could be used for comparison?
> 
> I also found out that BlastEm also doesn't suffer from this issue. Too bad libretro BlastEm crashes while fading in to the screen in the screenshot.

I'm familiar with picodrive. I use that core on RetroArch to play it. How do I change the core to PicoDrive on Bizhawk? I tried going to Config > Cores > Set libretro core... and using PicoDrive's libretro core and nothing happens.

**Comment by getCursorsExe** [comment] 2023-01-03 07:56
You have to clear out entire gamedb_sega_md.txt file (not delete it).

**Comment by getCursorsExe** [comment] 2023-01-03 08:49
Unforunately, this requries the core being in the cores selection list, which is not there, and it will not be there.

**Comment by StickyChannel92** [comment] 2023-01-03 09:20
Understood. Turns out I can make loading a certain ROM with a different core semi-permanent, as it saves it to the Recent ROMS menu.

Thanks for the help! :)

**Comment by YoshiRulz** [comment] 2023-01-03 12:49
>> How do I change the core to PicoDrive on Bizhawk?
>
> You have to clear out entire gamedb_sega_md.txt file (not delete it).

While it's true you can't pick PicoDrive in the UI, the gamedb can override the core preference with the 8th field (counting from 1).
https://github.com/TASEmulators/BizHawk/blob/00d450075e0760e17ddc874e90cd37fd014818e9/src/BizHawk.Emulation.Common/Database/Database.cs#L141-L145
e.g.
```
$> cat gamedb/gamedb_user.txt
2C41FD7372068FA86B3A1B2DDF03514253D0C2CA		Sonic Mega Mix (S1 Hack)	GEN				PicoDrive
$> cat -A gamedb/gamedb_user.txt
2C41FD7372068FA86B3A1B2DDF03514253D0C2CA^I^ISonic Mega Mix (S1 Hack)^IGEN^I^I^I^IPicoDrive$
```

---

Leaving this open as this hack is in the gamedb, indicating support.

**Comment by getCursorsExe** [comment] 2023-01-03 18:25
Well, BizHawk's PicoDrive core is the only way to play homebrew Genesis games that don't work on hardware. `ForcedCore` cannot be disabled normally.

**Comment by YoshiRulz** [comment] 2023-01-03 18:32
I have no idea what any of that means.

**Comment by getCursorsExe** [comment] 2023-01-03 18:37
But still, games like Sonic 1 Omochao Edition refuse to boot on Genplus-gx, but it does in PicoDrive. If people who make homebrew or ROM hacks relied on working on hardware, it would be a completely different story.
I don't know what to say anymore.

**Comment by nattthebear** [comment] 2023-01-04 12:38
What does hardware do in this situation?

**Comment by ekeeke** [comment] 2023-01-04 12:50
>Upstream issue. GPGX in RetroArch suffers from this too. The emulator is erroneously making the game clear the M4 bit (2nd bit) of VDP 0x00 register (every frame, possibly). 

This is incorrect. The emulator does not 'make the game' clear this bit erroneously, it is the game hack which forgets to set this bit when writing to VDP register #0. On real hardware, leaving this bit cleared will result in dimmed colors as this forces some bits to 0 in CRAM returned 9-bit values, which is what you are experiencing.

> I suggest to make an setting to force this bit enabled as the current workaround.

The correct workaround would actually be to fix this ROM hack so it works on real hardware and accurate emulators. I am quite sure this was fixed in a later version (4.0 ?) though.

>Well, I made some experiments with gamedb and file extensions to make BizHawk load this game in BizHawk's PicoDrive. And, to my surprise...

Most MD emulators do not emulate that VDP hardware 'feature' as it is only meaningful  when debugging homebrew or ROM hacks and figuring if they will work correctly on real hardware.

**Comment by ekeeke** [comment] 2023-01-04 12:53
>What does hardware do in this situation

It behaves as in Genesis Plus GX. See this old issue report as reference: https://bitbucket.org/eke/genesis-plus-gx/issues/168/sonic-megamix-35-leaked-version-sonic-1

**Comment by YoshiRulz** [comment] 2023-01-04 13:31
Oh, thanks for the info. I'll mark this as a bad dump in the gamedb then.

**Closed** 2023-01-04 14:41 UTC
Labels: Core: Genplus-gx, As intended / #Won'tFix, Repro: Affects 2.8

**Comment by getCursorsExe** [comment] 2023-01-05 07:42
I still don't know why BlastEm is displaying this correctly.

**Comment by ekeeke** [comment] 2023-01-05 20:05
>I still don't know why BlastEm is displaying this correctly.

Simply because it does not emulate that bit function yet.

**Comment by getCursorsExe** [comment] 2023-04-08 11:20
BlastEm does emulate this, but the effects are simply invisible, possibly because Mike Pavone forgot to implement bit-wise color masking (I need to look at BlastEm code for a bit).
