### ISSUE TITLE
Add a new core

### ISSUE THREAD

**Issue by Elcya** [TASEmulators/BizHawk#3134] opened 2022-02-09 02:16 UTC
I want to know if you will add the Wii core when you say you are going to add a new core, so that I can play Wii Games on bizhawk instead of dolphin simulator

**Comment by YoshiRulz** [comment] 2022-02-09 03:18
Duplicate of #2653. We won't be adding Dolphin as a core anytime soon.

**Closed by YoshiRulz** 2022-02-09 03:18 UTC
Labels: Question/Support
