### ISSUE TITLE
Loading savestates break Super Mario 64 ROM Hacks

### ISSUE THREAD

**Issue by noddy360** [TASEmulators/BizHawk#3092] opened 2022-01-24 02:00 UTC
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
After loading a savestate while playing a Super Mario 64 ROM Hack, it can cause major issues with the game, from dying automatically, to the game freezing, to BizHawk itself crashing and closing. It mostly happens when I save a state in one area, and load it while I'm in a different area. For example, saving a state from the Castle Grounds and loading it from the inside of the Castle Lobby or the first level of the game.
I've used the Rice Video Plugin for the most part as that is the only plugin I can use in my computer. I can't use GLideN64, for example. The Jabo plugin in earlier versions of BizHawk causes the same results as Rice. It doesn't matter which of the 2 plugins I use. I also used the Angrylion plugin and the same results happened to me.

I've tried various SM64 ROM Hacks with various degrees of results:

- Super Mario Star Road: Deluxe Edition (Game freezes)
- SM64: Last Impact (Game freezes)
- Super Mario 74 Extreme Edition (Game freezes)
- Super Mario Bros. Super Show 64 (Game freezes)
- Chao Bandstand (Game freezes)
- SM64 The Green Stars (Game freezes + Instant Death)
- Melee Adventure 64 (Instant Death)
- Arcade Fighter 64 (Instant Death)
- Super Mario 64 Land (Instant Death + Graphical Glitches)
- B3313: Internal Plexus (Instant Death + Graphical Glitches)
- Star Revenge Redone (BizHawk crashes and closes)
- Waluigi's Taco Stand (BizHawk crashes and closes)
- Danganronpa 64 (Collission + Graphical Issues)
- Wheelchair Mario (Audio Stops Playing + Game freezes)

When I use Mupen-rr or even Project 64, savestates work just fine for me, so I don't know what's going on here.

It seems that this issue is not present in BizHawk 1.6.1, a very old version of the emulator.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Open BizHawk and Open ROM.
2. Choose a SM64 Hack ROM (any from the list above). For this example I will load B3313.
3. Load the ROM and choose a save.
4. Save a state in the Castle Grounds.
5. Enter the Castle through the main door.
6. Load the savestate you just made.

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
![B3313 v0 7 2022-01-17 23 19 25](https://user-images.githubusercontent.com/31973588/150709393-1b8415e0-013d-44ca-bcb0-ade5b64c11e6.png)

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 1.6.1; Win10; Intel
- BizHawk 1.13.2; Win10; Intel
- BizHawk 2.7; Win10; Intel
- BizHawk 2.8; Win10; Intel
- BizHawk dev build at 5e3e65a2a; Win10; Intel
- BizHawk dev build at ad82f4f21; Win10; Intel
- BizHawk dev build at 02e9fea0; Win10; Intel
- BizHawk dev build at aa099e0; Win10; Intel

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by getCursorsExe** [comment] 2022-01-24 17:57
This should have made it impossible to TAS them at all (maybe we should waterbox the core?).

**Comment by noddy360** [comment] 2022-02-20 06:01
Issue still persists in 2.8. However in B3313's example, the graphics are messed up and I warp below the stage, but it doesn't result in an instant death anymore. I can't test both Ares cores at this point in time.
![B3313 v0 7 2022-02-19 23 50 57](https://user-images.githubusercontent.com/31973588/154830633-6d064df0-b37c-4861-8ddb-0fab72b7fad4.png)
This will need further testing.

**Comment by YoshiRulz** [comment] 2022-02-20 11:17
> I can't test both Ares cores at this point in time.
> This will need further testing.

Please do. The "accuracy" core is probably immune from this thanks to Waterbox.

**Comment by nattthebear** [comment] 2022-03-09 15:51
If this is confirmed to be not an issue in Ares, we should just close it, as no one cares enough to fix whatever is needed in Mupen.

**Comment by YoshiRulz** [comment] 2022-05-07 14:00
Tried B3313 and Last Impact, the latter didn't make it past the title screen, the former loaded but had terrible rendering issues. But I didn't fall through the floor when loadstating. Leaving this open.

**Comment by noddy360** [comment] 2022-06-17 03:00
Just tested Super Mario 64 Land with the Angrylion plugin, and it's still happening.
![Super Mario 64 Land 2022-06-16 20 54 44](https://user-images.githubusercontent.com/31973588/174216189-77a1d480-55d6-4534-85d6-85798e2730b3.png)

**Comment by YoshiRulz** [comment] 2022-09-09 03:07
Confirmed, when the Expansion Pak is enabled for Mupen64Plus, the bugs and crashes in B3313, Last Impact, and Super Mario 64 Land no longer happen on loadstate. Maybe we should change the default to enabled, at least for games not present in the gamedb.

**Closed by YoshiRulz** 2022-09-09 03:07 UTC
Labels: Core: Mupen64Plus, Homebrew (console-verified), Homebrew, Repro: Affects 2.7, Core: Ares64

**Comment by CasualPokePlayer** [comment] 2022-09-09 05:41
So a savestate made without the expansion pack and loading that state with the expansion pack still enabled causes the game to crash, yet if it's enabled at all times it doesn't? That sounds like some issue with disabling the expansion pack outright.

**Comment by YoshiRulz** [comment] 2022-09-09 05:44
I didn't try that because I assumed loading a state with different sync settings would fail, and from https://github.com/TASEmulators/BizHawk/issues/3092#issuecomment-1240843456 it sounds like that is the case.

**Comment by CasualPokePlayer** [comment] 2022-09-09 05:48
With different sync settings the savestate would just be rejected (and if it were, it'd probably crash the emulator entirely). I only asked what occured when the sync settings matched. It sounds like from this issue if the expansion pack is disabled, then savestates are broken, yet if it was enabled, savestates aren't. This is assumingg the savestate save and load have the same sync settings. So this would indicate an issue with disabling the expansion pack.

**Comment by CasualPokePlayer** [comment] 2022-09-09 05:53
A look at the disable expansion pack code seems to indicate why this occurs: all "disabling the expansion pack" actually does is set some memory that tells the game the expansion pack is not present, and most games will abide by this and not try to access past the first 4MB. However the core still actually has the expansion pack present and makes no attempt to block writes by naughty games that ignore being told the expansion pack not present (no surprise hacks are affected by this). And savestate code will just ignore the latter 4MB of RDRAM, so this leads to an obvious desync here.

**Comment by getCursorsExe** [comment] 2022-09-10 07:13
**BUT**, in case of B3313, loading a savestate just after a few frames on startup (about at frame 12), major graphical glitches appear no matter if expansion slot is enabled or not.

**Comment by getCursorsExe** [comment] 2022-09-10 20:34
Should we reopen this until the RDRAM expansion bug is fixed?

**Comment by YoshiRulz** [comment] 2022-09-11 03:41
Mupen's savestates might not be correct, but I would still consider this a gamedb issue, because if the savestates worked properly you'd still need to figure out that the Expansion Pak is required and manually enable it. Adding gamedb entries for these romhacks with `expansionpak=1` would actually fix the problem, and I believe the current policy is to leave that to the user (or community) for romhacks.

**Comment by getCursorsExe** [comment] 2022-09-26 18:22
The Patch Pending label and Won't fix label isn't normally used at the same time. (Unless you mean something I don't understand)
