### ISSUE TITLE
Disc Controls functions missing from Nymashock core

### ISSUE THREAD

**Issue by DarkEvil1987** [TASEmulators/BizHawk#3179] opened 2022-03-12 22:29 UTC
I am doing a recording of Fear Effect for the PlayStation. Using the Octoshock core, I always had severe desync issues with that game, so I tried the new Nymashock core in BizHawk 2.8 for Windows and it's working perfectly as far as syncing goes.
But the menu Disc Controls function is not present. The hotkey for opening and closing the disc tray is also missing from the System tab of the Controllers menu as far as I can tell, while Octoshock still has it.
While the Next disc and Previous disc hotkeys are present, most probably know that the PlayStation expects the disc tray to be opened and then closed before any kind of disc swapping can occur, so the Next/Previous hotkeys don't work at the disc change prompt in that game, even though I used an XML file generated by the multi disc bundler.

I thought I might be missing something, so I did a search and found no one talking about it. It's not an insurmountable issue for somebody doing a longplay like me, I could just make a savestate on the disc change prompt, load the next disc and load that state, but I guess it would be a major issue for anyone doing a TAS of a multi disc game.

**Comment by CasualPokePlayer** [comment] 2022-03-12 23:20
The Disc Next and Disc Previous should be working here (if they're broken, it would affect other Nyma cores like Saturnus.

Maybe related to https://github.com/TASEmulators/BizHawk/issues/3047?

**Comment by DarkEvil1987** [comment] 2022-03-12 23:38
To add some precision, this is a 4 disc game and at the end of disc 1, without asking to save, it just demands disc 2 and waits forever, until the correct disc is present. While on that prompt, pressing disc next seemingly does nothing, perhaps freezes and the disc drive LED light does nothing, but pressing disc previous before anything else makes the on-screen prompt change to disc tray open. Pressing disc next after that seems to make it close the tray, there is disk LED activity, but it says wrong disc.

I know nothing, but my guess is that disc previous changes it to disc 4 and opens the tray at the same time, pressing disc next makes it switch to disc 1 and closes the tray at the same time. Pressing disc next twice before it tries to load the swapped disc, to hopefully get to disc 2 also results in it saying wrong disc. I did finally try to make a manual save state on that screen, switch the disc and load that manual state, then I press the disc previous and disc next buttons and the game loads as expected. Obviously, this method can't be done in one contiuous movie file though. I can provide saves and movie files later if it helps?

**Comment by nattthebear** [comment] 2022-03-13 12:51
When it asks you to switch disk 1 to disk 2, what happens if you do <prev>, wait, then <next> twice fast?

**Comment by DarkEvil1987** [comment] 2022-03-13 16:06
I'm including a save state for anyone that might find use of it near the change disc screen for disc 1 to disc 2, game validated as Fear Effect (USA).

I tried different combinations of button presses on the disc change screen.

1. PREV/NEXT once: After prev, "DISC COVER IS OPEN" appears in the game screen, like on a real PlayStation when pressing the open button with this game. There has been no Disc Drive LED Light activity since the beginning of that screen. If I press next once after that, there is some disc activity after like 2 seconds, as if I had just closed the disc cover on the real machine and it was reading, a very short while later it says "WRONG DISC", which is expected if the current disc is not disc 2.

2. PREV/NEXT/NEXT: If I press prev, then with human reflexes press next twice, it still says "WRONG DISC" in what I find to be the same amount of time as if I had pressed next just once. There's plenty of time for somebody to press next twice before "WRONG DISC" appears, but I did also try to do it beyond most/all human capabilities by using frame advance to press next twice 1 frame apart, 2 frames apart and 3 frames apart, but it all went to "WRONG DISC".

3. NEXT: If the first key pressed is next after the disc change screen appears, the screen doesn't move a pixel, no disc activity and pressing prev doesn't work anymore, no controller buttons do anything either (they're not supposed to do anything anyway on that screen), the game seems stuck, even though the expected behavior, once disc 2 is inserted and the disc cover is closed, is to start up a loading screen after just a couple of seconds. Same thing if one presses next before prev after it has displayed "WRONG DISC", the game is stuck and prev doesn't work in any way anymore.


I also tried something else...

The disc change screen is different from the rest of the game in that it will only respond to two commands, opening the disc cover to change the screen prompt and closing the disc cover to make it start reading the disc. In a situation where the game is already constantly reading the disc without expecting a disc cover open/close, pressing next on disc 1 makes it start playing all videos from disc 2, so I know the next button is at least really switching the current disc from disc 1 to disc 2. I just think it isn't sending the proper signal that the disc change screen expects to start reading it.

Even stranger, on disc 1, if I press prev during the Eidos intro video, it freezes and waits, as if the disc cover was open on the real machine. Then pressing next makes it reload the intro video and disc 1 plays as usual. Pressing prev, then next twice, same thing, game reloads the intro video and disc 1 plays normally. In fact, after pressing prev on that screen, even dozens of attempts to press next doesn't make it switch to disc 2 in any manner.

[Fear Effect (USA).Nymashock.QuickSave0.zip](https://github.com/TASEmulators/BizHawk/files/8239901/Fear.Effect.USA.Nymashock.QuickSave0.zip)

**Comment by nattthebear** [comment] 2022-03-13 16:39
Got it, thanks, that rundown is very helpful.  FYI, the way the disks are laid out in the Nyma core right now is `[EMPTY, DISK 1, ..., DISK N]`, so hitting PREV on Disk 1 actually just puts you to an open tray with no disk inserted.  My hope was that PREV NEXT NEXT would work for going 1->2 while triggering open, but if that doesn't work even with precise 2 frame advance, then it's never going to work.

I'll have to add a separate open/close tray button, although this will invalidate existing movies.

**Comment by DarkEvil1987** [comment] 2022-03-13 18:01
Glad to help with any information I can, knowing personally not much about programmation.

Even though I can confirm that this particular issue is new to the Nymashock core when compared to the Octoshock core and adding open/close should be a fix for this issue I encountered at the end of DISK 1, I now see the relevance of issue #3047 as mentioned by [CasualPokePlayer](https://github.com/CasualPokePlayer). I do think that your suggestion of PREV/NEXT/NEXT with the correct timing might have worked to simulate disc open and change to DISK 2, but doesn't because the Multi-disk bundler kind of only remembers two discs or something like that.

Using the Eidos logo trick to confirm which disc is currently active, i can see that on DISK 1, if I press PREV first, it does go to a position that I will now call EMPTY according to your information. Now EMPTY and DISK 1 are stuck in memory. If I press NEXT, it goes back to DISK 1. Any further presses of PREV or NEXT will only make it switch as far as EMPTY or DISK 1. Similarly, if I press next first on DISK 1, the two discs in the loop are instead 1 and 2, any further presses of PREV or NEXT will only make it switch between DISK 1 and 2. This is probably why nothing worked on the disc change screen, because if the loop is EMPTY and DISK 1, it can't go to DISK 2 ever. If the loop is DISK 1 and 2, it can't go to EMPTY ever to simulate the tray being opened first, which that screen needs. In that current state, it means DISK 3 and 4 are even further from reach.

**Comment by fhelwanger** [comment] 2022-05-29 00:14
I'm having the same issue on FF9. Disc 1 to Disc 2 worked fine, but Disc 2 to Disc 3 is not working.

Doing some search I think I found the problem on the source code.

1. The `SwitchCds` function is only called when `prev` or `next` are `true`: https://github.com/TASEmulators/BizHawk/blob/9a8be9d727abd5768cbaa2b86d9c744c976cd634/waterbox/nyma/NymaCore.cpp#L132-L133
2. Inside `SwitchCds`, it goes to the next disc only if `wasNext` is `false`: https://github.com/TASEmulators/BizHawk/blob/84e195659c47fdf8b617777a1504efe5cffb169e/waterbox/nyma/cdrom.cpp#L123-L152

The problem is, after it goes to the second disc, `wasNext` will always be `true`, unless you go back to disc 1, but if you go to disc 2 again it'll remain `true` and thus will be impossible to go to disc 3.

I believe if the `if` before calling `SwitchCds` is removed the `wasPrev/Next` control will work, because it'll set them to `false` when both are `false`.

Sorry if it's more complicated than that, I couldn't test and make a PR because I don't have a dev environment to build it right now, but it seems like the cause.

**Comment by nattthebear** [comment] 2022-05-29 00:37
Makes sense.  I don't think the `if (prev || next)` conditional should exist; `SwitchCds` should be called every frame.

**Comment by CasualPokePlayer** [comment] 2022-05-30 05:27
Fixed in 58c28aefbaaa74e1c3a2a5b9bae4b1d5724a365d

**Closed by CasualPokePlayer** 2022-05-30 05:27 UTC
Labels: App: EmuHawk, Core: Nymashock
