### ISSUE TITLE
[F.Rq.] Pass gamepad rumble/haptics through to host (Mupen/Octoshock)

### ISSUE THREAD

**Issue by hfc2x** [TASEmulators/BizHawk#1756] opened 2019-12-11 17:51 UTC
Hello there. I've been using this emulator to test some games, and I realized that while there's an option for the controller pak to be set to Rumble Pak, there's no rumble on the controller whatsoever. I'm playing on Windows 10 64-bit, and I'm using an Xbox One controller through USB. The games don't seem to detect the Rumble Pak as connected either, even if the option is checked. 

Could an option for configuring it be added? Mostly, because Mupen64plus appears to support rumble if the pak is configured to be Rumble Pak.

**Comment by greysondn** [comment] 2020-01-16 23:29
Just the obligatory "Yes, I would use this" remark. Although N64 is typically casual play from me, if that matters for the emu's development priorities.

**Comment by YoshiRulz** [comment] 2020-01-16 23:45
@Asnivor had the host controller wired up for this IIRC. The roadblock to this is that our virtual controller code was written with the assumption that controllers are for *input*, i.e. nothing would ever be sent from the virtual console to a virtual controller. A new design is required for allowing `int`/`float` feedback(s) alongside `bool` and `float` inputs. I'm thinking `int` because it could be used for sound (Wiimote eventually?) as well as rumble. To that end, NDS emulation might benefit from an `int` *input* for the mic.

also this
> &lt;natt> rumble should shake the window imo

**Comment by InfamousKnight** [comment] 2020-01-21 18:08
Not sure if its related, but buck bumble requires rumble pak and and it seems the analog controls or any movement doesnt seem to work. I cant navigate the menus nor move up down left or right while in game. Buck bumble seems like a good tas candidate too.

**Comment by YoshiRulz** [comment] 2020-01-21 18:29
@InfamousKnight The Rumble Pak emulation works fine. Go into `N64` > `Controller Settings...` and swap out the 1st controller's pak. Check your controller keybinds, there's both analog-to-analog and digital-to-analog.

**Comment by abishur** [comment] 2020-02-10 18:07
@YoshiRulz I tried to do this using an official Nintendo N64 controller and a Raphnet N64->USB adapter.  Rumble works with PJ64 and N-Rage for PJ64: 2.5.2.202 but not with Bizhawk (although the controller itself does work, just not the rumble pak).  Is there a way to swap input plugins?

**Comment by YoshiRulz** [comment] 2020-02-11 09:32
@abishur The Rumble Pak is emulated correctly by Mupen64Plus, but its value is discarded and not used by the host controller. That's what this feature request is asking for.

**Comment by zeromus** [comment] 2020-02-11 10:09
floats are fine for sound. floats are USED for sound. and if youre not using floats, you're using 16bit values that fit in a float. however, we shouldnt let rumble get stopped waiting for a design that can pipe sound to a wiimote. that will be 100 times harder than wiring some crappy rumble support.

**Comment by YoshiRulz** [comment] 2020-02-11 10:21
Just needs core integration:
https://github.com/TASVideos/BizHawk/blob/4e5b763c3833127af5e420f8dbfee9dddc10b65d/BizHawk.Client.EmuHawk/Input/OTK_Gamepad.cs#L358-L362

**Comment by Meerkov** [comment] 2020-05-24 09:56
Same request, but for PSX.

**Comment by YoshiRulz** [comment] 2020-05-24 10:12
Rumble from Octoshock should also be possible. Upstream uses XInput on Windows and libinput on Linux. Only the DualShock has rumble on upstream (the Japanese Dual Analog Controller also had rumble, but `dualanalog` will emulate the American version).

**Comment by Meerkov** [comment] 2021-03-24 18:21
This feature would be really cool. Is there something I can do to help? It sounds like we need to debug the callback?

**Comment by YoshiRulz** [comment] 2021-03-24 22:45
For Octoshock? No idea. For Mupen, I'm convinced the problem is on the unmanaged side, so someone with C++ experience will need to open our fork in VS and look into it. I can rebase the WIP branch if needed.

**Comment by Meerkov** [comment] 2021-07-20 05:31
GhostlyDark confirmed that #2680 fixes this for N64. (And as a corollary, #2683 does not).

I started looking at Octoshock back in April, but Octoshock was a lot more complicated to figure out, so I didn't want to get too deep into it while still waiting for this merge...

**Comment by YoshiRulz** [comment] 2021-07-21 00:19
Mupen's rumble support is all wired up and mostly working in dev builds from 664ab7fab. Leaving this open for Octoshock.

**Comment by Eggo-dotcom** [comment] 2022-01-24 05:38
No vibrations here on 2.7

**Comment by YoshiRulz** [comment] 2022-01-24 05:42
You need to be using DirectInput, insert a Rumble Pak into the virtual gamepad, and then bind the feedback channel to your physical gamepad.

**Comment by Eggo-dotcom** [comment] 2022-01-24 05:45
> You need to be using DirectInput, insert a Rumble Pak into the virtual gamepad, and then bind the feedback channel to your physical gamepad.

Tried all that but xinput here. Dont own direct input controllers. Very uncommon these days i think.

Will xinput ever be considered?

**Comment by YoshiRulz** [comment] 2022-01-24 05:48
I meant that you need to have the "DirectInput+XInput" option selected in `Config` > `Customize...`. I can't say whether it will work with a specific gamepad or joystick.

**Comment by Eggo-dotcom** [comment] 2022-01-24 05:51
> I meant that you need to have the "DirectInput+XInput" option selected in `Config` > `Customize...`. I can't say whether it will work with a specific gamepad or joystick.

Gotcha. Will try again. Tried with official mx xbox 360 and xbox1 controllers. Couldnt get anything to do it. Will report back when i retry

**Comment by Meerkov** [comment] 2022-01-24 05:56
N64 games rumble just fine for my Xbox 360 controller, so it's probably your set up.

**Comment by Eggo-dotcom** [comment] 2022-01-24 11:12
> N64 games rumble just fine for my Xbox 360 controller, so it's probably your set up.

Is it wireless? Are you on windows 10 21h1? First time ever im having trouble with force feedback on anything. Ill check again after work tonight some time.

**Comment by Meerkov** [comment] 2022-01-24 16:38
@Eggo-dotcom Wired. Windows 10.

@YoshiRulz Maybe we should open a new bug for PS2 rumble, and close this one as "fixed". Then if people have issues with the rumble, they can file a new bug (e.g. if their controller isn't supported or whatever). This bug thread is going to get awfully confusing if we hold it open for Octoshock while other people are discussing N64 compatibility issues.

**Comment by Eggo-dotcom** [comment] 2022-01-25 01:53
> @Eggo-dotcom Wired. Windows 10.
> 
> @YoshiRulz Maybe we should open a new bug for PSX rumble, and close this one as "fixed". Then if people have issues with the rumble, they can file a new bug (e.g. if their controller isn't supported or whatever). This bug thread is going to get awfully confusing if we hold it open for Octoshock while other people are discussing N64 compatibility issues.

Got this to work once now and not again, dunno what im doing wrong

**Comment by CasualPokePlayer** [comment] 2022-09-17 08:37
Nymashock should be handled with https://github.com/TASEmulators/BizHawk/commit/de3878108177b73a4768af007b1deba89b8d3ed2

**Closed** 2022-09-17 09:16 UTC
Labels: Enhancement, App: EmuHawk, Core: Octoshock, Repro: Fixed/added in 2.6.3, Core: Nymashock, Repro: Fixed/added in 2.9 dev

**Comment by YoshiRulz** [comment] 2022-09-17 09:18
With #3359 fixed I'm confident in wontfix-ing Octoshock feature requests (that are aimed at casual play) and directing those users to Nymashock.
