### ISSUE TITLE
Game softlocks with current bsnes core, works fine on latest higan

### ISSUE THREAD

**Issue by ROMaster2** [TASEmulators/BizHawk#1078] opened 2017-12-21 04:41 UTC
Video of bug: https://www.youtube.com/watch?v=hTAPURmXn3Y (at 2:11)
Link to hack: https://www.smwcentral.net/?p=section&a=details&id=16696
Copy of relevant SRAM: https://drive.google.com/file/d/1nWm8Mqcx9aGw5VAsmZ-ftRP9b3J-F3Ay/view?usp=sharing

Works as intended on SNES console, higan v106, and the Snes9x core.
Does not work on Bizhawk 2.2.1's bsnes core, which is the only option to record movies with.

It may be an inaccuracy problem fixed in later versions. When going to grab a key in one of the levels, the core doesn't properly load said key and you're left unable to continue the level. I would be happy to compile a newer version of the core if there were instructions on how to do so.

**Comment by zeromus** [comment] 2017-12-21 23:27
Looks like a bug in the game due to random or zero initialization of memory. We might need to try a different seed or configuration for that. If anyone can actually build the bsnes core right now, youll want to change randomSeed() in libsnes.cpp.

**Comment by YoshiRulz** [comment] 2018-12-05 15:46
Reproducible on BizHawk 2.3 using the 2017-12-02 revision of the romhack, OS: Win10 Home 1709. Also this romhack kinda sucks.

**Comment by zeromus** [comment] 2018-12-05 16:01
see if you can ask the romhack author what’s weird about this key. it doesn’t look like an emulator bug to me.

**Comment by alyosha-tas** [comment] 2021-11-28 01:26
Does anyone still have the SRAM for this? I'm trying to test on v115 but it seems that level is several hours into the game.

**Comment by ROMaster2** [comment] 2021-11-28 03:13
Dunno why Google killed the link. https://drive.google.com/file/d/1PUeGnkT7VS8cC2zaqRn9WOcN7NqvPUjU/view?usp=sharing

If I remember correctly I was able to get around the key problem by moving a bit differently before entering the pipe. I'm guessing the hack's code for the key is a bit finicky.

**Comment by alyosha-tas** [comment] 2021-11-28 18:52
ok, i tried it v115 numerous times with various ways of enterring the pipe and it worked everytime in v115. So, closing.

**Closed by alyosha-tas** 2021-11-28 18:52 UTC
Labels: Bug (GoogleCode), Core: BSNES, Repro: Affects 2.3/2.3.1/2.3.2, Homebrew (console-verified)
