### ISSUE TITLE
BSNES: Actraiser desynchronization

### ISSUE THREAD

**Issue by Reinc01** [TASEmulators/BizHawk#2469] opened 2020-11-05 02:33 UTC
I recorded a playthrough of the SNES game Actraiser, but the input movie desynchronizes. I used the BSNES core of Bizhawk emulator for recording. I reported this issue in BSNES github, but was told to report this issue here instead.
[ActRaiser.USA.zip](https://github.com/TASVideos/BizHawk/files/5491588/ActRaiser.USA.zip)

edit: was bsnes-emu/bsnes#94 --yoshi

**Comment by zeromus** [comment] 2020-11-05 02:47
Did we really default "RandomizedInitialState" to true?

**Comment by nattthebear** [comment] 2020-11-05 03:28
> Did we really default "RandomizedInitialState" to true?

Before https://github.com/TASVideos/BizHawk/issues/1701 it was the only possibility, so it seemed like a sensible default.  There's no right answer to those sorts of initial state questions.

**Comment by zeromus** [comment] 2020-11-05 03:37
It is hard to decide but I would break the tie by making it simpler for tasers and defaulting to (choose any) deterministic pattern. This is because things are complicated enough for them already that we don't need to be adding to it; contrariwise with a non-random state gamers only notice problems very, very rarely for some known cases of badly-programmed games that magnify unlucky initial state into apparently buggy results and it is easy to tell them to change the option and continue playing. I think we would be left in a better condition if we changed it to default to false and wait for a new super offroad bug to tell them to change the option.

**Comment by nattthebear** [comment] 2020-11-05 12:34
No one complained about it until #1701, and even then it was only the TASVideos politics bloc, which is essentially impossible to please.  But let's not get away from things here:  If you want to change the default on that setting, either do it or make a ticket to discuss it.  This ticket already has a purpose:  It's about a desynchronization in ActRaiser.

Has anyone managed to reproduce this?  Like most desynchs, movie files don't hurt, but they're not enough by themselves  since they don't really contain what went wrong.  Better are instructions on how to make a movie that desyncs.

**Comment by alyosha-tas** [comment] 2021-11-11 20:05
issue for random state opened, this one is effected by the autofire issue which is fixed, closing.

**Closed by alyosha-tas** 2021-11-11 20:05 UTC
Labels: Core: BSNES
