### ISSUE TITLE
NESHawk: Famicom Jump 2 doesn't work until 2nd boot (same on fceux; is it normal?)

### ISSUE THREAD

**Issue by Yave-Yu** [TASEmulators/BizHawk#2139] opened 2020-06-16 10:54 UTC
Couldn't run _Famicom Jump II: Saikyou no 7 Nin_ with NesHawk core.
(ROM in GoodNES 3.23b pack)
![BizHawkGreenScreen](https://user-images.githubusercontent.com/54294476/84766029-bae1ba00-b002-11ea-9c21-4850bae56489.png)

**Comment by Spikestuff** [comment] 2020-06-16 11:13
Can't replicate (Hawk 2.4.2):
![image](https://user-images.githubusercontent.com/12412764/84767547-ff2a8580-b015-11ea-92b1-4b2647de5cd0.png)

I guess make sure you're using the NESHawk core?
Config > Cores > NES > NESHawk

**Comment by RetroEdit** [comment] 2020-06-16 11:13
I can replicate. I tried it on every NES emulator I could get my hands on with similar results. Weird.

**Comment by RetroEdit** [comment] 2020-06-16 11:42
Intriguing; it looks like something's wonky with BizHawk's core selection. Although the emulator claims to be running with NESHawk, maybe it's not actually unless you select it? I just did a clean extraction of BizHawk 2.4.2, and same issue. (The issue is permanently fixed by selecting an NES core; presumably that applies some change to the configuration file that prompts BizHawk to actually validate cores properly).

And look at this:

![QuickNES vs  NesHawk](https://user-images.githubusercontent.com/30182911/84770040-6a4c6b80-afc6-11ea-82ab-8013e86ef991.png)

The general UI presents NESHawk, but the menu selection shows QuickNES. From that, I think it's not properly detecting core overrides with the default BizHawk configuration.

I have yet to test dev builds.

**Comment by Yave-Yu** [comment] 2020-06-16 12:49
I'm sure it using NesHawk core, I never change it to terrible QuickNes core.
One weird thing: non-good dump (without [!]) of this game could run well.
![BizHawkOneMoreScreenshot](https://user-images.githubusercontent.com/54294476/84776463-e9679100-b012-11ea-9c73-5e6ed74fb6b1.png)

**Comment by RetroEdit** [comment] 2020-06-16 13:09
Have you retested with the good dump? The emulator needed a bit of prodding from me to select the right core, but after I selected it, the game worked fine.

**Comment by Yave-Yu** [comment] 2020-06-17 01:31
Yes, it works fine with good dump, just click "NesHawk" one time.

**Comment by zeromus** [comment] 2020-06-17 03:12
This game crashes when it first boots. Any time after the first boot, it will work correctly (due to an "initialized" state flag in the battery ram). The emulator core selection is a red herring; it has nothing to do with this. You can set neshawk, then DELETE the saveram, and boot the game again and it will freeze one more time. The same thing happens in fceux.

Other possibilities

1. The game is confused by our initial (all zero, probably) save ram contents. We have a crude system for specifying initial ram contents (see "Silva Saga" in the sources) so we could consider adding it -- IF we can prove different initial contents values fixes the game. I wasn't able to immediately prove it though (the 1st difference in execution was reading $6BBC but I tried changing the value of BBC at startup and saw no behavioural difference)
2. This is the way the game is supposed to work.
3. The game is confused by something else
4. The game is broken due to a bug (most likely, the mapper?) and after you play it for a few minutes it will fall apart.

If anyone finds out more lore about this, they're welcome to write about it here. I'll leave it open til someone finds out more one way or the other

**Comment by alyosha-tas** [comment] 2021-11-11 14:42
This does appear to be the same problem as silva saga (interpretting zeros as bad save data.) It looks like it 'loads' the save but then jumps to SRAM for execution but it has the wrong values so crashes.

Starting everything at 0xFF seems to work fine.

**Closed** 2021-11-11 14:43 UTC
Labels: Core: NesHawk, Priority: Poop, Question/Support
