### ISSUE TITLE
Issue in assigning Shift as one of the controls

### ISSUE THREAD

**Issue by CJPsychic** [TASEmulators/BizHawk#3365] opened 2022-08-21 02:50 UTC
Summary: Shift gets released when another button is pressed.

Host Env.
- BizHawk dev build https://github.com/TASEmulators/BizHawk/commit/98a8cdf693a580a3453486bc2dbcce8e375d6f15; Win10 Pro
- BizHawk 2.8; Win 10 Pro and Win 8.1

- BizHawk 2.7; Win 10 Pro and Win 8.1 doesn't have this issue (shown in video below)

This video should (hopefully) cover everything https://youtu.be/OKkgJBKLvsU

Its mentioned in issue #3184 but I don't think it has proper documentation there

**Comment by YoshiRulz** [comment] 2022-08-21 03:42
Duplicate of #3327? Looks similar based on the input display.

**Comment by CJPsychic** [comment] 2022-08-21 04:22
Oh yeah, it seems to be the same type of bug.

Didn't know it has been posted already, thank you very much.

**Closed** 2022-08-21 15:08 UTC
Labels: App: EmuHawk, Repro: Regression from 2.7
