### ISSUE TITLE
[GPGX] CRAM memorydomain is scrambled

### ISSUE THREAD

**Issue by zeromus** [TASEmulators/BizHawk#3662] opened 2023-05-15 18:24 UTC
When viewed in the hex editor, you will see e.g. $01FF for white. that's 9 bits scrambled into a more convenient format for emulation, with RGB all packed in the bottom. That same white should be $0EEE, probably, due to the strange MD palette format: https://segaretro.org/Sega_Mega_Drive/Palettes_and_CRAM

this is probably super annoying to fix, but until it's fixed, I would suggest nuking that memory domain from view because it's wrong and misleading and may even be hiding information (the meaning of the unused bits is unclear, but theyre probably hooked up). then again the VDP viewer may be using the memory domain (is there any way to hide them from the tools but use them internally?)

**Comment by YoshiRulz** [comment] 2023-05-16 01:26
Possibly duplicate of #2901.

**Comment by zeromus** [comment] 2023-05-16 02:21
oh yeah same thing for sure. it's just basically inspecting a very well-baked memory buffer instead of the raw cram data.
I guess it's possible that the device really only has the exact amount of ram required and they're just wired up to the bus nybble-wise. thats pretty clever (easier to manipulate nybbles than 15bits packed rgb). To do this right, we'd probably have to implement a memory domain via callbacks instead of generic buffer peeking and reconstruct the data same as the emulator's vdp_ctrl.c does. It's not really very hard. If this theory is true it means we don't have to worry about the unused bits, as they simply arent hooked up to anything. for instance, writing FFFF should read back as 0EEE. I feel sure that's how GPGX will work.

**Comment by CasualPokePlayer** [comment] 2023-05-16 03:17
I would guess this would be these formulas in vdp_ctrl to use here:
https://github.com/TASEmulators/BizHawk/blob/f11b5bc9c4d13538149cdc11abf3605dfa01673f/waterbox/gpgx/core/vdp_ctrl.c#L2703-L2707
https://github.com/TASEmulators/BizHawk/blob/f11b5bc9c4d13538149cdc11abf3605dfa01673f/waterbox/gpgx/core/vdp_ctrl.c#L2154-L2158
Should be trivial to implement this all on the C# side without any modifications to the code. Don't worry about VDP Viewer either, that goes through the more internal `gpgx_get_vdp_view` here and does not use memory domain API.

**Comment by zeromus** [comment] 2023-05-16 03:45
yeah thats the formulae

**Comment by getCursorsExe** [comment] 2023-05-16 10:40
This scrambling doesn't occur in PicoDrive32x, but CRAM in that core is only 0x40 bytes long!

**Closed** 2023-05-19 02:09 UTC
Labels: Core: Genplus-gx
