### ISSUE TITLE
Implement Libretro Settings

### ISSUE THREAD

**Issue by Sonia-7** [TASEmulators/BizHawk#3487] opened 2022-12-09 01:04 UTC
Sorry for another request in a row, but this will probably be the last one in a while. I wonder if you guys could add a region switch setting for that core under "Libretro Settings"? That would get around the one core rebooting issue that went unresolved on #3482.

**Comment by CasualPokePlayer** [comment] 2022-12-09 02:04
Renaming this to just implementing libretro settings in general. The way libretro has settings means we don't exactly get to pick and choose what settings are exposed, we would have to handle their system entirely to have any settings.

**Comment by Sonia-7** [comment] 2022-12-09 03:18
That would be great. I actually wanted full libretro settings from the beginning, but was worried if it'd be too much to ask so I decided to keep it small.

**Comment by CasualPokePlayer** [comment] 2022-12-09 07:27
Actually, this is a dupe of https://github.com/TASEmulators/BizHawk/issues/2854

**Closed by CasualPokePlayer** 2022-12-09 07:27 UTC
Labels: Request: Feature/Enhancement, re: Libretro
