### ISSUE TITLE
External Save RAM Fails in Mupen64Plus Core

### ISSUE THREAD

**Issue by GaucheArtist** [TASEmulators/BizHawk#3378] opened 2022-09-03 07:41 UTC
**Summary:**
I converted an `.sra` file from Project64 into an `.srm`, which worked in the Mupen64Plus core of RetroArch. Having transferred save RAM to BizHawk from different emulators in the past, I knew this should be as simple as renaming the `.srm` file to the appropriate `.SaveRAM` extension. However, BizHawk fails to read the save RAM and will not display any save data, overwriting the `.SaveRAM` file with this new empty save RAM.

**Environment:**
I've tested this across several Windows builds from the current 2.8 to BizHawk 1.13.2, and they all display the same problem. Another user (#3122) has reported similar issues with no feedback offered.

**Additional Files:**
Included for testing and investigation are 2 save RAM files -- the `.srm` that worked in Mupen64Plus core on RetroArch and which I tried renaming for BizHawk, and a fresh `.SaveRAM` that was created by BizHawk when launching the game.

[Save RAM.zip](https://github.com/TASEmulators/BizHawk/files/9482138/Save.RAM.zip)

**Comment by YoshiRulz** [comment] 2022-09-03 08:50
Closing as duplicate of linked Issue.

**Closed by YoshiRulz** 2022-09-03 08:50 UTC
Labels: Question/Support
