### ISSUE TITLE
GameShark SP not supported?

### ISSUE THREAD

**Issue by ArmadstheDoom** [TASEmulators/BizHawk#3901] opened 2024-04-23 19:09 UTC
### Summary
[//]: # So I do not know if this is a bug on my end, a lack of feature that's been added, or if this is an innate problem with the emulator, so I will explain my reasoning and confusion, as I've not found anything via googling it or looking through the problems that are open or closed here. 

I know that 'gameshark' as it was known was actually a bunch of things, however I have had no problem using it in bizhawk for gbc games, and I've not had issue with the codes in other emulators that use the same cores. To test this I downloaded retroarch with the mGBA core, and they worked. 

The test codes I used for this were for Fire Emblem: The Sacred Stones. The two master codes are these: 
00006777000A
10001BE00007
These follow the pretty standard 8 and 4 formula, so I figured they should be accepted. But I get an error when I try to use them, and as I said, I have no idea if that error is because I'm actually trying to use a feature that doesn't exist, I'm making a mistake that causes it, or there's something else going on. Again, I tried googling the error itself, tried googling fixes for it, and I looked through the open and closed threads, and it doesn't seem like anyone else is having these issues or maybe I'm clueless. 

So I'm not sure if this is a feature request or a bug/error; I'm not someone who knows too much about vram editing beyond the extreme basics. I know the converter works for gbc games, so I assumed it was just me making a mistake. Is this something that is fixable or is this an emulator feature request? 

### Repro
[//]: # 
1. open a gba game. 
2. attempt to convert a 'gameshark' code using the code converter
3. have error message repeated as many times as you have lines in the box

### Output
[//]: # 'input error' 
'codebreaker/gameshark sp/xploder codes are not yet supported'

### Host env.
[//]: #
- BizHawk 2.9.1 windows 10 x64

[//]: #
![Untitled-1](https://github.com/TASEmulators/BizHawk/assets/116344093/cb70aaa7-059e-4c2f-ac47-88438eaad447)

**Comment by YoshiRulz** [comment] 2024-04-23 19:17
This is one of our clearer error messages! A converter for that kind of code hasn't been written. See https://github.com/TASEmulators/BizHawk/issues/1367#issuecomment-1784086902 for a workaround.

Calling this a duplicate of #897.

**Closed by YoshiRulz** 2024-04-23 19:17 UTC
