### ISSUE TITLE
Doesn't detect/support Hotkeys with Multiple button keypress

### ISSUE THREAD

**Issue by DNS** [TASEmulators/BizHawk#3731] opened 2023-08-13 02:38 UTC
BizHawk doesn't detect/support Multiple button keypress (Hotkeys).
If the "config.ini" edited manually to:

```
    "Quick Load": "X1 Start+X1 LeftTrigger",
    "Quick Save": "X1 Start+X1 LeftShoulder",
    "Previous Slot": "X1 Start+X1 DpadUp",
    "Next Slot": "X1 Start+X1 DpadDown",
```

It still fail to detect Xinput keys combination.
It only able to detect if only using Keyboard combination [Ctrl/Alt/Shift key] + [OtherKeys]

So if the user only play using a controller (no keyboard), they will not be able to use Hotkeys for save/load state, etc.
Other emulators (eg: Mesen & Duckstation) support this feature.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.9.1 (x64); Win10 Ent 22H2 64-bit; Intel/AMD

### Screenshots

BizHawk doesn't support Hotkeys with Multiple keypress
![Tweaked config ini](https://github.com/TASEmulators/BizHawk/assets/37093/716b5ad6-b874-448a-9128-d8b22fc1d86b)

Mesen support Hotkeys with Multiple keypress
![Mesen hotkeys](https://github.com/TASEmulators/BizHawk/assets/37093/b78fafac-625a-4efc-9443-3f45d3c224e9)

**Comment by YoshiRulz** [comment] 2023-08-13 03:18
Duplicate of #2981.

**Closed by YoshiRulz** 2023-08-13 03:18 UTC
Labels: Enhancement, App: EmuHawk
