### ISSUE TITLE
No sound sample rate adjuster?

### ISSUE THREAD

**Issue by Yave-Yu** [TASEmulators/BizHawk#3444] opened 2022-11-09 04:07 UTC
![BH20221109120601](https://user-images.githubusercontent.com/54294476/200736092-d1403f26-4f0a-464b-9bde-1507796555ae.png)

**Comment by YoshiRulz** [comment] 2022-11-09 04:09
Duplicate of #2492.

**Closed** 2022-11-09 05:04 UTC
Labels: Request: Feature/Enhancement, App: EmuHawk
