### ISSUE TITLE
gens plus gx defaults issue

### ISSUE THREAD

**Issue by Shinobi-1987** [TASEmulators/BizHawk#3262] opened 2022-05-30 19:09 UTC
Genesis Plus GX is set default to 6 button controller.

This causes issues with some games even on real hardware.

Set default to 3 button. No issues with 100% of library.

Example. When using 6 button controller by default with mrs pacman on real hardware or here controls wont work correctly impossible to play.

Having a default control that breaks some titles doesnt make sense when the other default control breaks no titles

**Comment by YoshiRulz** [comment] 2022-05-30 19:13
Duplicate of #2775.

**Closed** 2022-05-30 19:13 UTC
Labels: App: EmuHawk, Repro: Fixed/added in 2.9 dev
