### ISSUE TITLE
Genesis SetCpuRegister() not implemented please implement

### ISSUE THREAD

**Issue by Cokie1** [TASEmulators/BizHawk#3248] opened 2022-05-18 21:09 UTC
[FeatureNotImplemented]
		public void SetCpuRegister(string register, int value)
		{
			throw new NotImplementedException();
		}

**Comment by YoshiRulz** [comment] 2022-05-19 07:24
Duplicate of #3043. (Sorry for implying you needed to make this; my searches were for "Lua" so I missed the existing one.)

**Closed by YoshiRulz** 2022-05-19 07:24 UTC
Labels: Request: Feature/Enhancement, Core: Genplus-gx

**Comment by Cokie1** [comment] 2022-05-21 00:25
No worries 😉
