### ISSUE TITLE
EmuHawk consumes extra GPU while paused

### ISSUE THREAD

**Issue by Meerkov** [TASEmulators/BizHawk#3737] opened 2023-08-15 00:59 UTC
Confirmed on 2.9 and 2.8
https://github.com/TASEmulators/BizHawk/commit/e731e0f32

![image](https://github.com/TASEmulators/BizHawk/assets/8139496/626efb9b-ae52-4a50-8891-b94fdc62ec97)
Strangely, BizHawk seems to consume about 8% of my GPU while paused with no game loaded.

What's stranger is that if I *unpause* so that it runs at 60 FPS (also with nothing loaded), then it only consumes around 6.5% of my GPU.

![image](https://github.com/TASEmulators/BizHawk/assets/8139496/562bc5dc-e2be-45f0-b860-10f9982a4b28)

This seems inefficient.

Paused, with a PS1 game loaded (and resized to roughly the same size as the default): around 14%
![image](https://github.com/TASEmulators/BizHawk/assets/8139496/926b92d9-461a-46d5-96fd-4ac55546c389)

Running, with a PS1 game loaded: 12%
![image](https://github.com/TASEmulators/BizHawk/assets/8139496/6e8d1c07-bbc3-44e5-b407-2636068865d4)

It looks to me like while Paused, Emuhawk actually is busywaiting and consuming extra GPU when it likely should not be doing anything.

**Comment by YoshiRulz** [comment] 2023-08-15 01:00
Duplicate of #3268?

**Comment by Meerkov** [comment] 2023-08-15 01:02
![image](https://github.com/TASEmulators/BizHawk/assets/8139496/a9ef2ccf-a29d-4064-98f8-4d0c412d9eba)
I'm not running Unthrottled, but maybe I'll take this moment to update and see if it reproduces.

**Comment by Meerkov** [comment] 2023-08-15 01:07
Still reproduces on 2.9 https://github.com/TASEmulators/BizHawk/commit/745efb1dd

**Comment by CasualPokePlayer** [comment] 2023-08-15 02:21
While Paused, it's still going to presenting and that is going to in fact use the GPU. If it didn't, then stuff like Lua scripts drawing on screen wouldn't work. Also, the OSD wouldn't be able to update unless it presenting new frames. This is all expected behavior.

**Closed by CasualPokePlayer** 2023-08-15 02:21 UTC
Labels: App: EmuHawk, Repro: Affects 2.8, Repro: Fixed/added in 2.9.2 dev

**Comment by YoshiRulz** [comment] 2023-08-15 02:26
If we had a dirty flag for the OSD and drawing layers, would we be able to skip repaints while paused?

**Comment by CasualPokePlayer** [comment] 2023-08-15 02:33
Actually, misread the issue. BizHawk *probably* shouldn't have more GPU taken up while it is paused. However, given what the actual code does when paused, I'm not quite sure if it is the fault of BizHawk here, but maybe more GPU drivers trying to optimize BizHawk's rendering weirdly? Render() is not affected by the pause flag here, the only thing it tangentially does is update a lot of what ends up getting rendered, perhaps the GPU drivers are increasing usage when duplicate stuff is given to it?

**Comment by CasualPokePlayer** [comment] 2023-08-15 02:34
> If we had a dirty flag for the OSD and drawing layers, would we be able to skip repaints while paused? (We sort of do, or did, already under Mono. Not when paused, but when a modal dialog was open.)

We could *maybe* do that. But even then, trying to skip repaints at all could be bad, as that messes up presentation consistency and cause frame judders for some users.

**Comment by CasualPokePlayer** [comment] 2023-08-15 02:50
Ah, it seems like this code is likely the cause here:
https://github.com/TASEmulators/BizHawk/blob/c10d2927ca6cc00f781883c3828cdef304c33c06/src/BizHawk.Client.EmuHawk/Throttle.cs#L33-L45
The FPS display ends up frozen for this duration as there isn't a way to track FPS since throttling skips its logic while the emulator is paused. Throttle ends up always sleeping for 10 ms at least, or otherwise makes it run at a pseudo 100 fps. Perhaps we could just change it to 17 so it runs more like 60 FPS? /shrug

**Comment by YoshiRulz** [comment] 2023-08-15 02:54
Don't even need 60 fps while paused, could be 20. (I guess using the platform framerate would be ideal, but that sounds annoying to implement.) IIRC hotkeys are already broken at low speeds so such a change won't break anything further.

**Comment by CasualPokePlayer** [comment] 2023-08-15 02:57
20 is perhaps a bit low, we do want the app to be responsive, and message pumping (and thus GUI events) is on the main thread, so our throttling also throttles those.

**Comment by CasualPokePlayer** [comment] 2023-08-15 21:53
While it's probably not much of an issue while paused (as the only updates would be input display and lua drawing with emu.yield()), not consistently presenting can sometimes end up causing frame judder.
