### ISSUE TITLE
[F.Rq.] Expose Genplus-gx' built-in NTSC filter

### ISSUE THREAD

**Issue by ghost** [TASEmulators/BizHawk#3977] opened 2024-07-24 17:11 UTC
Gensplus-gx expose built in ntsc filter

I believe its as simple as exposing and makes some titles much better

**Comment by CasualPokePlayer** [comment] 2024-07-26 00:50
It's not as simple as exposing, it's simply not supported for our configuration (using 32bpp rendering, the NTSC filter is only supported for 16bpp rendering).

**Comment by YoshiRulz** [comment] 2024-07-26 01:17
I was already thinking of closing this since our (unwritten) policy is not to use upstream's filters/upscaling/"goodizers".

**Closed by YoshiRulz** 2024-07-26 01:17 UTC
Labels: Request: Feature/Enhancement, App: EmuHawk, Core: Genplus-gx, Ghost'd

**Comment by CasualPokePlayer** [comment] 2024-07-26 01:40
An NTSC filter isn't really a "goodizer", it's more akin to color correction options.

Granted, an NTSC filter can probably be made into some generic shader if anything.

**Comment by YoshiRulz** [comment] 2024-07-26 04:17
So this is a duplicate of #3391?

**Comment by vadosnaprimer** [comment] 2024-07-26 08:37
> I was already thinking of closing this since our (unwritten) policy is not to use upstream's filters/upscaling/"goodizers".

There's no such policy.

**Comment by nattthebear** [comment] 2024-07-26 12:11
Please don't duplicate an issue after you didn't get the answer you wanted the first time (https://github.com/TASEmulators/BizHawk/issues/3672).

> There's no such policy.

There kind of is; why waste time adding a core specific post-process when the same work could be used to add something that would work on all cores?

**Comment by vadosnaprimer** [comment] 2024-07-26 14:41
> > There's no such policy.
> 
> There kind of is; why waste time adding a core specific post-process when the same work could be used to add something that would work on all cores?

Because the shader way is almost unusable, since libretro shaders that have those features won't run on hawk. So per-core options seem to be the only way for regular users who can't port RA shaders to hawk.

**Comment by 007mesen** [comment] 2024-07-29 15:03
Was simply asking for the same treatment as the a7800 core dunno why everyone against it but ok

**Comment by 007mesen** [comment] 2024-07-30 04:12
Isint this as simple as just allowing the user to turn orn the filter already in gens plus gx?? Why block it on purpose i dont understand

**Comment by CasualPokePlayer** [comment] 2024-07-30 04:43
> It's not as simple as exposing, it's simply not supported for our configuration (using 32bpp rendering, the NTSC filter is only supported for 15bpp or 16bpp rendering).

**Comment by nattthebear** [comment] 2024-07-30 18:59
> Because the shader way is almost unusable, since libretro shaders that have those features won't run on hawk. So per-core options seem to be the only way for regular users who can't port RA shaders to hawk (or fix hawk to support then, which would absolutely solve this the right way, obviously).

I'm comparing developer time working on this one core vs developer time spent on the frontend, so the comparison would be with improving RA shader support or adding some other method to do this in the frontend.
