### ISSUE TITLE
Bizhawk audio crackles/suffers severe performance loss while minimized

### ISSUE THREAD

**Issue by Nicholas-Steel** [TASEmulators/BizHawk#3008] opened 2021-11-28 17:09 UTC
It looks like minimizing Bizhawk while playing an N64 game causes what _seems_ to be a severe performance issue for the emulator with the audio buffer sounding severely starved/crackly.

Minimizing the emulator via the Minimize button, the "Show desktop" button on the taskbar or double-clicking the application on the taskbar to minimize it all cause this issue. Switching to another program without minimizing Bizhawk is fine.

Windows 10 21H2
Geforce 1070Ti
Realtek ALC1220 audio
Direct3D, Vsync Enabled
[config.txt](https://github.com/TASEmulators/BizHawk/files/7613960/config.txt)

split from #1279

**Comment by zeromus** [comment] 2021-11-28 20:27
no problem here for me. maybe your os power or GPU configuration is set to snooze minimized windows and the GPU rendering can't keep up. Trying a demanding core (bsnes or octoshock) that doesnt have gpu acceleration would help prove that

**Comment by Nicholas-Steel** [comment] 2021-11-29 04:43
You're not wrong that it's some kinda power saving, I've been searching for months on how to stop it ever since upgrading from an Intel i7 920 to a Ryzen 3700X (I'd love it to run at the advertised base clock speed at minimum during lite tasks). When focused the emulator causes CPU cores to hover around 1.5GHz, when minimized they drop to 825MHz (Ryzen Master monitoring, Task Manager always says 4GHz no matter what when there is a work load).

I've already tried changing the Windows Power Plan to High Performance and switching off any and every power saving setting I can research in the BIOS (so far the Cool 'n' Quiet equivalent setting remains elusive). Anyways, thanks for confirming it's a Me issue.

**Comment by Nicholas-Steel** [comment] 2021-11-29 06:31
Assuming you haven't tried the included configuration file:

Disable Clock, Audio and Vsync Throttle.
Enable Vsync.

Minimize the emulator.

**Comment by zeromus** [comment] 2021-11-30 21:34
no problems for me here on windows 7. What about the "some kinda power saving" thing? I can't observe any reduction of the CPU speed with it minimized, even when I pin it to two cores so that I'm sure which two to watch.

**Comment by Nicholas-Steel** [comment] 2021-12-03 12:26
> no problems for me here on windows 7. What about the "some kinda power saving" thing? I can't observe any reduction of the CPU speed on my 5950x with it minimized, even when I pin it to two cores so that I'm sure which two to watch.

I'm not sure what the cause is, only that I can reliably reproduce it. I think my ramblings about power settings were misleading and should be disregarded. I can make a video clip of the issue if you'd like?

**Comment by zeromus** [comment] 2021-12-03 18:05
We need reproductions from other users, since the simplest explanation is still your system being misconfigured to inappropriately snooze minimized windows

**Comment by Nicholas-Steel** [comment] 2021-12-04 13:33
It's only when using the Direct3D graphics API with the Vsync setting enabled. If I switch to OpenGL or turn off the Vsync setting the problem ceases to happen.

I've also tried setting this to Background Programs in an attempt to resolve it: 
![image](https://user-images.githubusercontent.com/11567846/144711392-dc95196d-884a-487f-8e7b-1c154e990c12.png)

**Comment by Morilli** [comment] 2021-12-04 13:48
Can reproduce. While I try to figure this out, I can recommend
1. not using vsync if it doesn't work 
2. not minimizing the window lol or
3. using alt+esc instead

**Comment by Morilli** [comment] 2021-12-04 14:00
First google result: <https://www.gamedev.net/forums/topic/641298-directx-window-drops-to-30fps-when-it-is-not-the-foreground-window-in-win7/>

Seems this is not a bizhawk problem, and especially not a new problem. It may be the nvidia drivers or whatever intentionally throttling a background window, assuming that its fps are not crucial (which they wouldn't be, weren't fps directly tied to audio and game speed in emulation).
Profiling also shows suspiciously large render times:
![image](https://user-images.githubusercontent.com/35152647/144712241-bc7e269a-ce7e-4097-bd37-72a83892b19b.png)

The best approach here is probably to force-disable vsync on minimize or call this intended behavior.

**Comment by YoshiRulz** [comment] 2021-12-04 14:07
What happens if you enable `MainForm.InvisibleEmulation` while minimised?

**Comment by Morilli** [comment] 2021-12-04 14:21
> What happens if you enable MainForm.InvisibleEmulation while minimised?

Does not seem to work. Setting display mode to "absolute zero" does maintain 60fps though.

**Comment by zeromus** [comment] 2021-12-04 17:07
Forcing the logic internally to "absolute zero" while minimized is a good idea. I endorse this if anyone wants to take a stab at it

**Comment by Morilli** [comment] 2024-06-02 16:28
This should be resolved in the latest dev version since the upgrade to Direct3D11.

**Closed by Morilli** 2024-06-02 16:28 UTC
Labels: Enhancement, App: EmuHawk
