### ISSUE TITLE
Feature Request: Lock Mouse to Window.

### ISSUE THREAD

**Issue by Rwfrk** [TASEmulators/BizHawk#4019] opened 2024-09-02 23:04 UTC
I'd like to be able to lock my mouse to the emulated window when it supports touch such as with a DS core running.

**Comment by CasualPokePlayer** [comment] 2024-09-02 23:21
Think this is a dupe of https://github.com/TASEmulators/BizHawk/issues/3573?

**Closed** 2024-09-03 00:35 UTC
Labels: Request: Feature/Enhancement, App: EmuHawk
