### ISSUE TITLE
Sonic 2 Delta Next cannot be played anymore in Genplus-gx

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#2812] opened 2021-06-20 20:57 UTC
In older versions of BizHawk like 2.3.2, we could play Sonic 2 Delta Next ROM (prototype of Sonic Delta 40Mb). However, in current version, everything has completely changed and Sonic 2 Delta Next ROM cannot be played anymore in Genplus-gx. I don't know what caused something like this to happen, but it works fine in older versions.

Force-loaded this ROM with PicoDrive (32X) core, and it works just fine.

**Comment by YoshiRulz** [comment] 2021-06-20 20:58
Don't link copyrighted material in here please.

**Comment by getCursorsExe** [comment] 2021-06-20 20:59
It don't think it's a copyrighted material, since it is an archive.

**Comment by getCursorsExe** [comment] 2021-06-20 21:02
I don't think it's a copyrighted material anymore, since this happens to be an archive.

**Comment by getCursorsExe** [comment] 2021-06-20 21:10
Now, if we look at Z80 RAM, we see that probably almost 75% of the RAM is filled with 51C8, and this is responsible for preventing it from being played.

**Comment by CasualPokePlayer** [comment] 2021-06-20 21:10
You don't "lose" copyright until a _very_ long time. This in particular is a ROM hack of Sonic 2 so Sonic 2's copyright applies, which isn't expiring until 2087. Link a patch to the hack, not the ROM.

**Comment by getCursorsExe** [comment] 2021-06-20 21:12
Well, I think someone is gonna steal my password for this.

**Comment by getCursorsExe** [comment] 2021-06-20 21:14
I need to close this issue before this happens.

**Comment by nattthebear** [comment] 2021-06-21 00:46
Probable duplicate of https://github.com/TASVideos/BizHawk/issues/2626.  I know one's sanic 2 delta and the other is sanic 3 delta, but some homebrew mapper detection garbage is sure to be the culprit.

**Comment by getCursorsExe** [comment] 2021-06-21 09:54
Reopening this, since it doesn't make sense to close this thread at this point.

**Comment by YoshiRulz** [comment] 2022-01-22 11:23
This isn't the place to discuss how copyright law works or should work, but for the record:
A romhack is a ["*derivative work*"](https://en.wikipedia.org/wiki/Derivative_work) where (in theory) the romhacker holds the copyright to any major additions or changes, and the original developer holds the copyright to the rest of it. But without the original developer's permission, the romhacker (maybe) [forfeits their copyright](https://en.wikipedia.org/wiki/Derivative_work#Lawful_works_requirement) and (maybe) can't share it without infringing on the original developer's copyright. Which is illegal. So romhacks are distributed as patches, because patches are generally understood as "only the added/changed parts" and thus non-infringing (maybe).
When a game isn't available anymore, the copyright isn't automatically waived. It becomes an ["*orphan work*"](https://en.wikipedia.org/wiki/Orphan_work). So even if a romhacker put their work into [the public domain](https://en.wikipedia.org/wiki/Public_domain) before disappearing, *and* the original developer had also disappeared, sharing a (patched) romhack would still be copyright infringement.
If you're wondering why there are so many caveats to this, it's because 1. copyright law is really complicated, and international copyright law is really really complicated; 2. the law predates software, and lawyers are still playing catch-up with reality; and 3. the specifics are [based](https://en.wikipedia.org/wiki/Case_law) on [precedent](https://en.wikipedia.org/wiki/Precedent) and there's not enough precedent. Also I am not a lawyer, I just have too much free time.

**Comment by nattthebear** [comment] 2022-01-22 12:09
Not sure how I missed this being reopened.  Closing as duplicate of #2626, just as I indicated the first time.  If we fix that one and this one is still broken, feel free to call me names then.

**Closed by nattthebear** 2022-01-22 12:09 UTC
Labels: Core: Genplus-gx

**Comment by getCursorsExe** [comment] 2022-05-25 20:39
There is not even an IPS patch for this hack. It seems that IPS patches are only done on Nintendo games, literally.
