### ISSUE TITLE
Emulation accuracy problem with BSNES core

### ISSUE THREAD

**Issue by Atari2** [TASEmulators/BizHawk#2504] opened 2020-12-04 10:36 UTC
This issue is very simple to explain yet may be very hard to fix considering that BSNES cores aren't as easy to port over, however:

Recently I was playing a SMW modified rom and some custom code that was put into the rom wasn't working properly. I thought it would be an issue with the code itself but after trying out various emulators, I've concluded that the issue lies in BizHawk using v87 of BSNES which is a very old build.

I've tried with the following emulator/cores:

- SNES9x 1.60 -> Works fine and code does what it should
- BizHawk 1.3/2.3/2.5.2 -> Works fine on SNES9x core, doesn't work at all on BSNES core and (only for BizHawk 2.5.2) doesn't work on Faust core.
- BSNESv115 -> Works fine and code does what it should

The major reason on why I think the issue is with the old core and not the code itself is mainly because going to a newer version of BSNES (v115 in this case, but I also tried v112 and it worked on that one aswell) made it work, therefore it means that an inaccuracy in some emulation code was fixed going from v87 (what BizHawk uses) to v112/v115.

If you are curious about what code isn't working exactly, please refer to [this](https://www.smwcentral.net/?p=viewthread&t=104346) . The issue is described in the last paragraph (the not working blocks are the custom blocks with the code that was inaccuratly emulated, and switching emulators made them work, as aforementioned).

**Comment by YoshiRulz** [comment] 2020-12-04 10:45
see also #1078, #1198

**Comment by nattthebear** [comment] 2020-12-16 00:15
Do we have any knowledge of what the problem is, and whether it's an inaccuracy or simply something broken the game is doing that newer bsnes has hacks for?  How does this behave on real hardware?

**Comment by Atari2** [comment] 2020-12-16 11:57
> Do we have any knowledge of what the problem is, and whether it's an inaccuracy or simply something broken the game is doing that newer bsnes has hacks for? How does this behave on real hardware?

The code that was inserted in the game works perfectly fine on real hardware, it was tested both on SuperNT with SD2SNES and on SD2SNES with a real SNES. [This](https://www.twitch.tv/videos/787584087?t=01h09m09s) is a video where you can see the custom blocks working on real hardware (the custom blocks are the yellow blocks that poof when touched with the key), they just act as a normal solid block (e.g. they don't poof) on the version of BSNES that BizHawk uses (v87 iirc) but they work fine in newer BSNES versions, as stated in the initial post.

**Comment by alyosha-tas** [comment] 2021-11-27 18:37
played through the hack in v115 and key temple plays just fine. Eventually v87 will be removed, so closing this one.

**Closed by alyosha-tas** 2021-11-27 18:37 UTC
Labels: Core: BSNES, Repro: Fixed/Added in Upstream Stable, Homebrew (console-verified)
