### ISSUE TITLE
fullscreen not fullscreen......

### ISSUE THREAD

**Issue by Eggo-dotcom** [TASEmulators/BizHawk#3083] opened 2022-01-20 20:17 UTC
BizHawk is going to full screen borderless window not exclusive full screen.

**Comment by YoshiRulz** [comment] 2022-01-21 02:34
Duplicate of #825.

**Closed by YoshiRulz** 2022-01-21 02:34 UTC

**Comment by Eggo-dotcom** [comment] 2022-02-12 13:20
The reason i bring this up is in current windows versions no exclusive full screen leads to what i guess  would describe as frame jitter. Not alot but if you play something with lots of scrolling for a long period of time in a emulator with exclusive vs bizhawk on win 10 or 11 without exclusive it becomes painfully obvious. This is not a system specific issue i hPpen to have many many many computers at my disposal and can replicate this 100% of the time regardless of cpu model and video card model and ram amount.

**Comment by Shinobi-1987** [comment] 2022-02-19 15:06
Using retroarch or mednafen to get true exclusive full screen then going to bizhawk shows instantly the disadvantages of not true exclusive full screen under current win 10 and 11

**Comment by Shinobi-1987** [comment] 2022-03-09 01:57
Hmmm under speedskip enable vsync….  This is something i thought would ve under display and i assumed was always on with the vsync statement in displaytabs. This solved my issues
