### ISSUE TITLE
Nintendo DS games don't save

### ISSUE THREAD

**Issue by brskiiii** [TASEmulators/BizHawk#3285] opened 2022-06-22 11:44 UTC
I'm playing a DS game and when I save my game, it says my game was saved but when I reboot the game, the save is gone and I have to start over. Tried both Pokemon Diamond and HeartGold.

Although, randomly it did seem to save ONE TIME. I was playing for like 45 minutes then I saved. Later I booted it back up and my save file was there but it said 0:03 which is when I attempted to save earlier, but not 0:45 like it should have been. I was messing with some settings and stuff. I think I even flushed SaveRAM around that time but not sure if that had anything to do with it.

It seems to save just fine when I play a GBA game, though.

**Comment by YoshiRulz** [comment] 2022-06-22 11:45
Duplicate of #3165?

**Comment by CasualPokePlayer** [comment] 2022-06-22 11:48
Sounds like #3165, you need to manually flush SRAM every time (or just use 2.9 dev).

**Closed by CasualPokePlayer** 2022-06-22 11:48 UTC
