### ISSUE TITLE
Windows 10: Cheats dialog is unreadable when OS is in dark mode (high contrast black)

### ISSUE THREAD

**Issue by webbedspace** [TASEmulators/BizHawk#3541] opened 2023-01-30 10:49 UTC
### Summary
The screenshots speak for themselves.

### Repro
One: turn on High Contrast Black as the system theme
![image](https://user-images.githubusercontent.com/83939/215456456-c1493b3f-791a-42be-8016-c73b2602c650.png)
Two: open Cheats dialog
![image](https://user-images.githubusercontent.com/83939/215456278-e812b376-e41f-4db9-af00-8cfd913a9b3a.png)
Notice there are 3 cheats but only 1 is remotely readable.

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk dev build at b11bb4f; Win10;

**Comment by YoshiRulz** [comment] 2023-01-30 11:04
Duplicate of #1617.

**Closed by YoshiRulz** 2023-01-30 11:04 UTC

**Comment by webbedspace** [comment] 2023-01-30 12:04
Sorry, tried searching for "dark mode" and couldn't find that one.

**Comment by CasualPokePlayer** [comment] 2023-01-30 15:03
This isn't actually dark mode to be clear, dark mode is a separate thing (which BizHawk does *not* honor due to WinForms not bothering here), this is a more special "high contrast" mode. which WinForms does honor (and it can be [detected apparently](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.systeminformation.highcontrast?view=netframework-4.8))
