### ISSUE TITLE
Weird snap sound in Super Street Fighter 2 (USA) on BSNES core

### ISSUE THREAD

**Issue by Zimond47** [TASEmulators/BizHawk#3021] opened 2021-12-06 23:05 UTC
Tested with Bizhawk 2.6.3 and 2.7

I just noticed a weird snap sound right at the beginning of _Super Street Fighter 2 (USA)_ before the Capcom intro. First I thought it was just something in my videorecording, but no, it can be recreated.

I tested it with all 4 cores and this snap sound only occurs with the regular Bizhawk Core. Snes9x, Faust and BSNES 115 dont make that snap sound.

I didnt notice any other sound problems, just this one at the beginning. It's of course an absolutely minor thing but maybe it could be something that happens to other games as well and wasn't noticed before. 

PS : Also tested changing the sound outputs. Same on all three.

**Comment by YoshiRulz** [comment] 2021-12-07 03:03
If it doesn't affect the new BSNES, #wontfix.

**Comment by zeromus** [comment] 2021-12-07 03:23
This is caused by "randomized initial state". Why are we enabling that by default?

**Comment by nattthebear** [comment] 2021-12-07 03:26
> This is caused by "randomized initial state". Why are we enabling that by default?

Presumably the TASVideos politicians yelled at us until we changed it.

**Comment by CasualPokePlayer** [comment] 2021-12-07 11:02
> > This is caused by "randomized initial state". Why are we enabling that by default?
> 
> See [#2996 (comment)](https://github.com/TASEmulators/BizHawk/issues/2996#issuecomment-966618258); having some kind of (deterministic?) randomization is supposedly most accurate to a real console.

Well note that comment more pertained to BSNESv115, but it does still mean the problem isn't randomized initial state on principle, but whatever particular pattern from lsnes that was shoved into BSNES is the issue. Even so, disabling randomized initial state just means you'll probably just get problems with different games rather than fixing the problem. Upstream/BSNESv115 seems to even have hotfixes just override the entropy setting in case the game is known to be problematic with some randomized state, which seems to be a nicer solution anyways (can't win em all, so hax the stragglers).

**Comment by Zimond47** [comment] 2021-12-08 14:00
> If it doesn't affect the new BSNES, #wontfix.

oops, my bad. So 115 is the new one. I see, it is just a testphase before making it the default BSNES core then? I thought it was some kind of fork specially made for some speedrunning purpose or something like that.

**Closed** 2022-05-05 12:52 UTC
Labels: Core: BSNES, As intended / #Won'tFix, Repro: Affects 2.7
