### ISSUE TITLE
Manually editing CRAM in Genesis does not work correctly

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#2901] opened 2021-08-08 17:26 UTC
Each time the game wants to change VDP Palette, it has to write to CRAM. However, unlike CGRAM in SNES, this does not work correctly when you manually edit CRAM. You will see no changes in most cases, but it might interrupt the game writing to CRAM, causing some palette glitches to happen.
This CRAM writing issue does not happen in PicoDrive, but there is another issue found in this core: the core only captures the first 0x40 addresses, even though there are actually 0x80.

**Comment by YoshiRulz** [comment] 2023-01-11 04:40
Reproduced by @Cokie1 on Discord. Pokes seem to have no effect, peeks seem to return garbage.
> I opened a genesis game in Bizhawk and Exodus. Compared the CRAM in hex editor and the Bizhawk Hex Editor shows CRAM not matching Exodus. Don't think Bizhawk CRAM info is correct. I have big endian checked and it doesnt appear to be the issue. It just seems different.
> ![screencap](https://cdn.discordapp.com/attachments/977013684146671698/1062582854170722424/image0.jpg)

**Comment by zeromus** [comment] 2023-05-16 02:23
#3662 definitely a dupe of this one

**Comment by CasualPokePlayer** [comment] 2023-05-19 02:31
Probably fixed with #3662 fixed

**Closed by CasualPokePlayer** 2023-05-19 02:31 UTC
Labels: App: EmuHawk, Core: Genplus-gx, Repro: Affects 2.8
