### ISSUE TITLE
Memory Offset Address in Biz Hawk 2.9.1

### ISSUE THREAD

**Issue by leomarx71** [TASEmulators/BizHawk#3908] opened 2024-05-01 04:13 UTC
Hello guys I needing help in developing autosplit for top Gear, I would like to user BizHawk 2.9.1 because it comes with Retroachievements... I am following the ASL from Pedro (my friend), but he also does not remember how he defined the values of ModuleMemorySize and memoryOffset from olders versions. Can you help how to find these state values for Core Bsnes ? Thanks in Advance

(P.S.: I'm posting here because I couldn't find any other communication channel from you)

https://github.com/pedro-walter/livesplit-autosplitters/blob/main/topgear.asl

        { 2453504, 0x36F11500240 }, // BizHawk 2.3
        { 7249920, 0x36F11500240 }, // BizHawk 2.3.1
        { 4726784, 0x36F11500241 }, // BizHawk 2.3.2
        { 4546560, 0x36F05F94040 }, // BizHawk 2.6.1
        { 4538368, 0x36F05F94040 }, // BizHawk 2.6.2
		{ ??????? , ????????? }, // BizHawk 2.9.1
		
![image](https://github.com/TASEmulators/BizHawk/assets/87551567/aebfaa45-582b-4688-8753-1fed36335f80)

**Comment by YoshiRulz** [comment] 2024-05-01 06:33
Duplicate of #1680. tl;dr: We don't support taking pointers to host memory in this way. That it works at all is coincidental.

**Closed by YoshiRulz** 2024-05-01 06:33 UTC
Labels: Question/Support
