### ISSUE TITLE
SuperGrafx broken graphics in 2.3

### ISSUE THREAD

**Issue by Cyorter** [TASEmulators/BizHawk#1303] opened 2018-08-29 03:38 UTC
Most SGX games have graphical glitches but works excellent in 1.13.2.
Aldynes and Daimakaimura are safe (I think)
![sgx](https://user-images.githubusercontent.com/42274825/44763909-441cb980-ab1b-11e8-8300-045938ffc815.png)

**Comment by Asnivor** [comment] 2018-09-26 09:37
@Cyorter @synnae Can you re-test this now using the latest dev build please?

https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Comment by Cyorter** [comment] 2018-09-30 02:34
![1941 - counter attack j 2018-09-29 22 06 54](https://user-images.githubusercontent.com/42274825/46252508-6d40aa80-c437-11e8-877f-c9e8fb858b88.png)
![daimakaimura j 2018-09-29 22 13 05](https://user-images.githubusercontent.com/42274825/46252450-b2181180-c436-11e8-818c-13ad83495724.png)
Sorry for the late, but after playing 5-10 minutes each game, I see it solved the major graphic problems! But there are still some minor problems in the graphics, in 1941 title screen, the big "1941" moves to the right and the top is glitched.
In Daimakaimura when black screen between the beginning scene and starting the level, there's a similar glitch on the top.
I still have to play even more Daimakaimura to being sure and test about sound but good job :)

**Comment by YoshiRulz** [comment] 2019-03-22 01:11
[regression 2.2.1 vs 2.3.1](https://imgur.com/a/dYsOb0N) courtesy of @EZGames69

**Comment by Asnivor** [comment] 2019-03-22 08:23
Yup, [this commit](https://github.com/TASVideos/BizHawk/commit/aa7cee1bb7d123f5ed9c136554bb8fae7d9d9b37) was done to fix some of the SGX bugs iirc. However, it caused problems in many other PCE games.

Eventually we just reverted it because nobody had the time/skills/inclination get all the PCE games fixed. Unfortunately, without a pretty good understanding of the PCE/SGX video system, fixing bugs for individual games in this core appears to result in some kind of nightmarish house of cards scenario.

So until someone steps up and takes this core on (or we waterbox something like mednafen's PCE module), all of these PCE/SGX bugs/issues are likely to remain.

**Comment by jjfmz42015** [comment] 2019-09-17 20:53
why hasnt mednaffen been water boxed?

**Comment by EZGames69** [comment] 2020-05-28 15:46
I have tested both 1941 and Ghouls n Ghosts in the newest waterboxed core and they do not have this issue.  PCEHawk in dev build still does have it however.

**Comment by alyosha-tas** [comment] 2021-11-24 14:22
I moved the remaining graphics bugs to the other PCE issue. #960 The regression that caused this initial report was fixed long ago, the remaining bugs are just ones similar to those in the main issue, closing.

**Closed by alyosha-tas** 2021-11-24 14:22 UTC
Labels: Core: PCEHawk, Repro: Affects 2.3/2.3.1/2.3.2, Repro: Regression from 2.2.x
