### ISSUE TITLE
GPU Churns while paused (2.9.1)

### ISSUE THREAD

**Issue by Meerkov** [TASEmulators/BizHawk#3928] opened 2024-05-27 06:27 UTC
I thought it would be worth opening a bug for this, because it does consume 10% of my GPU in a paused state which is kind of annoying.

If it needs new frames only for Lua scripts, would it be possible to skip that when no lua is loaded?

>              While it's probably not much of an issue while paused (as the only updates would be input display and lua drawing with emu.yield()), not consistently presenting can sometimes end up causing frame judder. For a buttery smooth experience, you want to consistently present new frames.

_Originally posted by @CasualPokePlayer in https://github.com/TASEmulators/BizHawk/issues/3737#issuecomment-1679669741_

**Comment by YoshiRulz** [comment] 2024-05-27 06:31
Is it any better in dev builds? (And is this not the same as #3737?)

**Comment by YoshiRulz** [comment] 2024-05-27 06:43
The host graphics system has changed a lot since the other issue was closed, so it's worth checking the resource consumption again. It should only take a few minutes to download a dev build and check it.

**Comment by CasualPokePlayer** [comment] 2024-05-27 07:51
It only consumes around 3-4% GPU while paused in latest dev (typically just around the same as an unpaused state anyways).

I'd consider that just as working as intended / won't fix, if just because the gain for lower GPU usage while paused is very negligible and a dirty detection system would need a considerable amount of complexity and likely would result in buggy code to figure out if things are dirty or not due to the amount of things that could affect that, also the situation is again not worse than unpaused. If you are extremely concerned about power usage, minimize the app.

**Closed by CasualPokePlayer** 2024-05-27 07:51 UTC
Labels: App: EmuHawk, Repro: Affects 2.9.1
