### ISSUE TITLE
BizHawk - FFMPeg crash on Star Wars N64

### ISSUE THREAD

**Issue by Meerkov** [TASEmulators/BizHawk#3052] opened 2021-12-31 08:46 UTC
### Summary
If you try to play Star Wars - Shadows of the Empire (N64), you will see that the game runs at 60 FPS, and yet still stutters.

Trying to use the Video exporter (ffmpeg) results in A/V desync error messages and BizHawk becomes unresponsive immediately.

( Bizhawk 2.7 )

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Load Star Wars - Shadows of the Empire (N64)
2. File > AVI/Wave > Record AVI / Wave > Choose File name
3. Unpause emulator
4. 
![image](https://user-images.githubusercontent.com/8139496/147812986-bebdefb8-a106-4e0b-87f6-ee3f38f3b2c0.png)
5. 
![image](https://user-images.githubusercontent.com/8139496/147812997-304594cc-89b1-4653-95e0-0b12edf72ff8.png)
6. 
![image](https://user-images.githubusercontent.com/8139496/147813006-eefaaca4-63f0-4e94-ad13-f708253cf7f3.png)
7. Bizhawk is unresponsive
8. Try again, this time, don't use AVI/Wav recording. Just play the game
9. Make sure you're using GLideN64 (video resolution 320x240 in the Plugin Settings).
10. See glitchy opening
![image](https://user-images.githubusercontent.com/8139496/147813077-f653926a-8a21-4376-aefd-ee83907f21ea.png)
11. Press A to continue
12. The audio sounds like it's broken/not running at 60 FPS. But if you look, you will see it is running at 60 fps.

13. Test the game in MUPEN64. It works fine.

**Comment by Meerkov** [comment] 2021-12-31 09:02
When was the last time the N64 upstream was pulled in?

**Comment by YoshiRulz** [comment] 2021-12-31 21:04
2014-ish, but the GLideN64 plugin specifically is more recent (see #1718).

**Comment by nattthebear** [comment] 2021-12-31 21:10
Duplicate of https://github.com/TASEmulators/BizHawk/issues/2603

**Closed by nattthebear** 2021-12-31 21:10 UTC
Labels: Core: Mupen64Plus, Repro: Affects 2.7

**Comment by Meerkov** [comment] 2021-12-31 21:29
Thanks, I see this is a dupe of 2 different issues. Hopefully more fire for the pile to get some updates :)
